### ISSUE TITLE
Add screen lock for autologin

### ISSUE THREAD

**Issue by HinzundKunz** [sddm/sddm#401] opened 2015-04-14 09:24 UTC
It would be great if you could set the screen to lock after autologin. It would reduce the felt boot time even further.

**Comment by int-ua** [comment] 2015-04-25 21:51
Duplicate, check https://github.com/sddm/sddm/issues/306#issuecomment-76474868 for a workaround.

**Comment by int-ua** [comment] 2015-04-26 09:09
What DEs can do that? I know only about KDE.

**Comment by plfiorini** [comment] 2015-05-16 21:56
Close as being duplicate of #306

**Closed by plfiorini** 2015-05-16 21:56 UTC
