### ISSUE TITLE
Hang on login screen

### ISSUE THREAD

**Issue by git-alex-voronin** [sddm/sddm#1330] opened 2020-11-20 07:26 UTC
I'm not sure if this is a bug with SDDM or some KDE problem, but sometimes login process hang on login screen. 
What I do:
1. Start laptop
2. Login screen appear
3. Type password
4. Push login button
5. Nothing happens (splash screen not appears)

The cursor moves, but nothing else reacts.

The problem often happened on the 5.9 kernel. 
My laptop uses hybrid graphics and I used the 455 driver before. But the problem appeared so often that I switched to the 450 driver. The problem appears less frequently, but it still happens almost every day.

Logs after SDDM update:
[inxi -Fxzc0.txt](https://github.com/sddm/sddm/files/5571854/inxi.-Fxzc0.txt)
[sddm_log_20_11.txt](https://github.com/sddm/sddm/files/5571857/sddm_log_20_11.txt)
[system_log_20_11.txt](https://github.com/sddm/sddm/files/5571860/system_log_20_11.txt)

Logs before SDDM update:
[sddm_18_11.txt](https://github.com/sddm/sddm/files/5571855/sddm_18_11.txt)
[sddm_18_11_2.txt](https://github.com/sddm/sddm/files/5571856/sddm_18_11_2.txt)
[system_log_18_11.txt](https://github.com/sddm/sddm/files/5571859/system_log_18_11.txt)

_Unfortunately, the problem doesn't always look the same. Before the update, the screen would go blank and the password entry screen would appear again and freeze after entering the password again. In addition, before the update, the splash screen sometimes appeared and hung on it._

**Comment by tpgxyz** [comment] 2020-11-20 09:43
Looks similiar to https://github.com/sddm/sddm/issues/1316

**Comment by Rudi3** [comment] 2020-11-20 14:15
I possibly had something similar after upgrading to [kde 5.20.3](https://bodhi.fedoraproject.org/updates/FEDORA-2020-d700fa11cf).

I had a black screen at times and at one point frozen sddm after login on my secondary monitor (with the screen unlocked). Also, it seems that there are two sessions created instead of one (I saw two on `seat0`).

And it wasn't really the same behaviour everytime I tried...

**Comment by Pointedstick** [comment] 2020-11-29 00:44
> ноя 20 08:44:43 nitro sddm[820]: Display server failed to start. Exiting

Yeah seems like a duplicate of https://github.com/sddm/sddm/issues/1316.

**Closed by Pointedstick** 2020-11-29 00:44 UTC
