### ISSUE TITLE
sddm 0.20.0 breaks multi-seat logind integration

### ISSUE THREAD

**Issue by Redeeman** [sddm/sddm#1791] opened 2023-09-12 14:10 UTC
Hello.

Upgrading from sddm 0.18.1 to 0.20.0 broke logind session registration for me for a second seat.

I have two gpu's etc, and run multi-seat where two seats are active at the same time, and with 0.18.1, both seats would be registered correctly with logind such that loginctl displays the following:

```
SESSION  UID USER     SEAT  TTY 
     c1    0 root     seat0 tty1
     c4 8000 user1 seat0     
     c5 8010 user2    seat1 
```

using 0.20.0, it only displays the following when both are logged in:

```
SESSION  UID USER     SEAT  TTY 
     c1    0 root     seat0 tty1
     c4 8000 user1 seat0     
```

This results in amongst other things XDG_RUNTIME_DIR not being set, and as such, pipewire does not work.

Gentoo patches various things, which it does for both 0.18.1 and 0.20.0: https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-misc/sddm/files

looking at my current (reverted back to 0.18.1), pam.d/sddm is set to substack for system-login, like this:
```
#%PAM-1.0

auth            substack                system-login
-auth           optional        pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so

account         substack                system-login

password        substack                system-login
-password       optional        pam_gnome_keyring.so use_authtok

session         optional        pam_keyinit.so force revoke
session         substack                system-login
-session                optional        pam_gnome_keyring.so auto_start
-session  optional  pam_kwallet5.so auto_start
```

**Comment by Redeeman** [comment] 2023-09-17 23:16
possibly also dupe of #1762 ?

**Comment by n3rdopolis** [comment] 2023-09-25 14:34
> possibly also dupe of #1762 ?

Seems like it

**Comment by Vogtinator** [comment] 2024-02-11 13:40
Ok, closing as duplicate

**Closed as not planned by Vogtinator** 2024-02-11 13:40 UTC
Labels: duplicate

**Comment by Redeeman** [comment] 2024-05-26 10:38
@Vogtinator Was it a mistake it was closed as "not planned"?

**Comment by Vogtinator** [comment] 2024-05-27 09:10
No, it's a duplicate of https://github.com/sddm/sddm/issues/1762.
