### ISSUE TITLE
Plasma 5.20 has Black desktop screen when using wayland in conjunction with SDDM

### ISSUE THREAD

**Issue by gbcox** [sddm/sddm#1335] opened 2020-11-29 01:47 UTC
Works fine with X, however when using SDDM with Radeon graphics, black desktop occurs.

When using GDM, Wayland and Radeon, also works fine.

Opened Fedora bug here:
https://bugzilla.redhat.com/show_bug.cgi?id=1897717

**Comment by torokati44** [comment] 2020-12-13 01:24
I have the same issue on two separate machines.

When switching to a textual console however (say, with Ctrl+Alt+F4), logging in there, then issuing `dbus-run-session startplasma-wayland`, Plasma loads and works just fine, on Wayland.

For me, after some time, a dialog pops up (on top of the black screen with only the cursor visible) asking for the password for my otherwise auto-connecting WiFi network.

On some occasions I see a crash report dialog, about `ksplashqml` segfaulting somewhere in Mesa, in `update_buffers` - this might be unrelated?

**Comment by torokati44** [comment] 2020-12-13 01:49
Well, based on this, I just tried editing `/usr/share/wayland-sessions/plasmawayland.desktop`, replacing the `Exec=` line with:
`Exec=/usr/bin/dbus-run-session /usr/bin/startplasma-wayland`
and not touching anything else. (Then I had to `sudo service sddm restart`, but simply rebooting would have been also fine most likely...)

Now I can log in to Plasma (wayland) just fine from SDDM as well.

The original line was:
`Exec=/usr/libexec/plasma-dbus-run-session-if-needed /usr/bin/startplasma-wayland`

That `plasma-dbus-run-session-id-needed` script contains this:
```
#!/usr/bin/sh
# Usage: plasma-dbus-run-session-if-needed PROGRAM [ARGUMENTS]
# If the session bus is not available it is spawned and wrapper round our program
# Otherwise we spawn our program directly
drs=
if [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]
then
    drs=dbus-run-session
fi
exec ${drs} "$@"
```

Perhaps something in this little wrapper goes wrong? Like it detects that `dbus-run-session` prefix is not needed, even if it is? I haven't tested it any further TBH...

**Comment by gbcox** [comment] 2020-12-13 03:36
I made the change as described in your post and then I rebooted the system.  When I tried to login via SDDM to Plasma Wayland, it took my password and then immediately presented the same SDDM login screen.  The only way I was able to login at that point was to select regular Plasma (not Wayland Plasma).  Did you try a system restart?

**Comment by gbcox** [comment] 2020-12-13 22:56
I also found this:  https://bugs.archlinux.org/task/66766
Don't know if it is related or not.

**Comment by torokati44** [comment] 2020-12-13 22:59
Yeah, this could be the reason for that wrapper script that starts dbus "if needed"?

**Comment by gbcox** [comment] 2020-12-13 23:22
Yeah, the plasma-dbus-run-session-with-needed was the solution for https://bugs.kde.org/show_bug.cgi?id=404335
If just caused a whack-a-mole situation.  I reopened 404335 pointing back to here and the Fedora bug.

**Comment by torokati44** [comment] 2020-12-14 11:46
I'd like to add that one of my machines (the desktop) indeed only has a Radeon (with the open-source amdgpu driver), while the other one (the laptop) is an Intel + Radeon hybrid, again, both with open drivers.
I'm not sure if SDDM on Plasma turns on or uses the Radeon in the laptop - it used to be disabled until I ran anything with `DRI_PRIME=1`, but lately it's always on...

**Comment by goeranu** [comment] 2020-12-30 23:16
For completeness, perhaps I should mention here too this happens to me on an F33 laptop with Intel graphics. I added more details in [KDE bug](https://bugs.kde.org/show_bug.cgi?id=404335).

**Comment by torokati44** [comment] 2020-12-31 00:07
Just a random thought... Could it _possibly_ be, that SDDM, being based on Qt, starts some sort of dbus broker daemon, which is detected by the session wrapper, but then is stopped when the login screen exits? Or... does SDDM exit at all when a session starts?

**Comment by gbcox** [comment] 2020-12-31 00:43
> Just a random thought... Could it _possibly_ be, that SDDM, being based on Qt, starts some sort of dbus broker daemon, which is detected by the session wrapper, but then is stopped when the login screen exits? Or... does SDDM exit at all when a session starts?

The way I understand all of this from reading: https://bugs.kde.org/show_bug.cgi?id=404335
is that you want everything to use the same dbus session.  If everything is working properly, that dbus session is handled by
systemd.  What the workaround referred to in comment #15 of the bug 404335 did was to create the script "plasma-dbus-run-session-if-needed" which does a verification that indeed a dbus session has been started.  If one has been started (which it should have been) then plasma is started via /usr/bin/startplasma-wayland.  However, if for some reason a dbus session doesn't exits, one is created via the dbus-run-session command and then plasma is started.

If you start plasma with dbus-run-session when a dbus-session has already been established, it's bad news as described at the beginning of 404335.  

We've looked at this from several angles now and all roads seem to point back to SDDM.  It appears that GDM has the logic in it to deal with an existing dbus-session, whereas SDDM does not.  Hopefully, the SDDM folks will take a look at this problem report and comment.  We're running out of time and Fedora is targeted to start using KDE wayland as default starting with F34.

**Comment by davidedmundson** [comment] 2020-12-31 01:01
>We've looked at this from several angles now and all roads seem to point back to SDDM.

The SDDM folks are the same as the KDE folks in that ticket. I am very unconvinced that sometthing in SDDM is wrong.

Right now the comments don't make any sense together, at which point it's impossible to draw conclusions.

>If you start plasma with dbus-run-session when a dbus-session has already been established, it's bad news

That is very true. But the idea that it's graphic card specific then doesn't add up, as nothing graphic card specific is over DBus.
Also, that code should no-op if there is a DBus session already, and what we know so far doesn't make sense.

**Comment by gbcox** [comment] 2020-12-31 01:24
> > We've looked at this from several angles now and all roads seem to point back to SDDM.
> 
> The SDDM folks are the same as the KDE folks in that ticket. I am very unconvinced that sometthing in SDDM is wrong.
> 
> Right now the comments don't make any sense together, at which point it's impossible to draw conclusions.
> 
> > If you start plasma with dbus-run-session when a dbus-session has already been established, it's bad news
> 
> That is very true. But the idea that it's graphic card specific then doesn't add up, as nothing graphic card specific is over DBus.
> Also, that code should no-op if there is a DBus session already, and what we know so far doesn't make sense.

Thanks for that clarification.  As far as graphics card specific, I'm assuming that all the people who have looked into this ticket have at least tried to reproduce it themselves and aren't having any issues, and I still haven't heard of anyone who has radeon graphics reporting that things work for them.  Today was the first day someone reported an issue with intel graphics.  The problem of course is that most people who try to use KDE Wayland and get a black screen don't screw with it and just fall back to X11.  Until someone gave give me specific instructions on particular information they need, all I can provide is anecdotal.

One thing has been confirmed and that is that GDM works and SDDM doesn't.

**Comment by gbcox** [comment] 2020-12-31 01:44
Oops, forgot one thing... 
`Also, that code should no-op if there is a DBus session already, and what we know so far doesn't make sense.`

I believe the code is no-op'ing.  In my instance, the string is not empty, so SDDM is invoking WITHOUT dbus-run-session.  Which is what we want... however, that's when we get a blank screen.  The conjecture on my part is that for some reason that created plasma session isn't working with the previously created dbus-session.  I can open up a terminal in the black screen session and enter commands, so if there is something I could provide which may be helpful, I will be happy to do it.

**Comment by davidedmundson** [comment] 2020-12-31 18:27
> I can open up a terminal in the black screen session and enter commands, so if there is something I could provide which may be helpful, I will be happy to do it.

Oooh!

In that case output of ~/.local/share/sddm/*.log and output of "env"

**Comment by gbcox** [comment] 2020-12-31 19:57
Thanks for the quick reply David.  Unfortunately, I couldn't find a .local/share/sddm directory.  I also looked in .kde, .config, .cache.  The only thing I could find on my system was at /var/log/sddm.log and it had a creation date of Nov 14 2017.  I've attached 2 text files showing the output of the env command.  env.txt as taken with the black screen.  envgdm.txt shows what it looks like on the working system when I use gdm.  Let me know if you can think of anything else for me to try that might help.


[envgdm.txt](https://github.com/sddm/sddm/files/5758181/envgdm.txt)
[env.txt](https://github.com/sddm/sddm/files/5758182/env.txt)

**Comment by gbcox** [comment] 2020-12-31 22:10
Here is the output from journalctl.  I tried to delete the obvious unrelated stuff.  Hope it helps.
[sddmjournal.txt](https://github.com/sddm/sddm/files/5758361/sddmjournal.txt)

**Comment by goeranu** [comment] 2021-01-02 11:15
> Just a random thought... Could it _possibly_ be, that SDDM, being based on Qt, starts some sort of dbus broker daemon, which is detected by the session wrapper, but then is stopped when the login screen exits? Or... does SDDM exit at all when a session starts?

I'm not sure if this answers the question, but I've verified the same dbus-broker is running before the `exec` line in `plasma-dbus-run-session-if-needed` and then later after the session has been started.

I also tried starting a `dbus-monitor` in the script, and comparing the output when starting from gdm and sddm. It differs a bit, but I haven't really understood if any of the differences are relevant. Would I just spam if I added the traces here, or would it help?

**Comment by gbcox** [comment] 2021-01-02 18:17
> > Just a random thought... Could it _possibly_ be, that SDDM, being based on Qt, starts some sort of dbus broker daemon, which is detected by the session wrapper, but then is stopped when the login screen exits? Or... does SDDM exit at all when a session starts?
> 
> I'm not sure if this answers the question, but I've verified the same dbus-broker is running before the `exec` line in `plasma-dbus-run-session-if-needed` and then later after the session has been started.
> 
> I also tried starting a `dbus-monitor` in the script, and comparing the output when starting from gdm and sddm. It differs a bit, but I haven't really understood if any of the differences are relevant. Would I just spam if I added the traces here, or would it help?

Probably wouldn't hurt... might be interesting to see.  Take a look at the sddmjournal.txt I posted.  Notice all the SDDM errors.  That isn't what you want to see in a log file. I checked and many of those errors were supposed to be already fixed.  I have the latest version from the Fedora repositories and suffice to say, they aren't.  I don't know if that is a packaging issue or whether the fixes just didn't work.  

Line 504 is where plasma-dbus-run-session-if-needed is invoked 
Line 532 things start abending

So obviously something is going on.

**Comment by davidedmundson** [comment] 2021-01-02 18:21
Some good news, this has found a lot.

```
Dec 31 11:37:13 charon audit[2108]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 pid=2108 comm="kactivitymanage" exe="/usr/libexec/kactivitymanagerd" sig=11 res=1
Dec 31 11:37:13 charon kernel: show_signal_msg: 90 callbacks suppressed
Dec 31 11:37:13 charon kernel: kactivitymanage[2108]: segfault at 300 ip 00007f24ed0bad50 sp 00007ffd1cd47e60 error 4 in libQt5XcbQpa.so.5.15.2[7f24ed0a5000+9e000]
```

If kactivitymanagerd dies, plasmashell won't boot.


Another very interesting thing to note in your env, you're using the wayland session. But kactivitymanagerd dies in the X plugin.

It implies the env that DBus/systemd has it out of sync?

Lets run:
qdbus --session org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager.Environment

to confirm.




Can I also have your exact plasma version? We had an issue at some point with syncing the env if the local env contained non basic characters. Systemd (which you'll be using for dbus activation on the default broker) just discarded all the env vars we sent it, which meant it couldn't find important things like wayland-0 and so on.

I added in a workaround for that, I thought before the release.

**Comment by gbcox** [comment] 2021-01-02 18:47
My plasma version is:  plasma-workspace-wayland-5.20.4-1.fc33.x86_64
This is the latest version the the Fedora repos.

I ran the qdbus --session command in the SDDM (broken) and GDM (working) environments, in case you needed them both.  I've attached the files.  Let me know if you need any more information.  Thanks again for your help!

[sddm.qdbus.query.txt](https://github.com/sddm/sddm/files/5760741/sddm.qdbus.query.txt)
[gdm.qdbus.query.txt](https://github.com/sddm/sddm/files/5760742/gdm.qdbus.query.txt)

**Comment by davidedmundson** [comment] 2021-01-02 19:05
That confirms the theory of what precisely where it is wrong \o/

So this is the root bug:
https://github.com/systemd/systemd/issues/16704

I added a downstream guard when we sync our update variables, it's in the version you are running but maybe it's not as robust as it needs to be. 

Where does this 
"BASH_FUNC_ml%%=() {  module ml "$@""... in your env come from?

As a test could we try dropping that?

In the meantime I'll see if I can find somewhat to export what you dumped above into my env. I have a manual unit test for this thing, so hopefully that should be easy once I can reproduce it.

**Comment by gbcox** [comment] 2021-01-02 19:31
Thanks!  I have no idea what they are or why they are there.  I did a quick google search and found this:
https://access.redhat.com/discussions/4124031  "RHEL 8 has sick disturbed unholy bash env vars set like BASH_FUNC_module%% and BASH_FUNC_switchml%% ??? "  Looks like Fedora at some point did the same.  Maybe some Redhat folks could comment.

**Comment by gbcox** [comment] 2021-01-03 18:12
Hey David,

I opened:  https://bugzilla.redhat.com/show_bug.cgi?id=1912046
and apparently systemd has agreed to allow non-posix names:  
https://github.com/systemd/systemd/pull/17188

The bad part is that it's in the next release of systemd.  I'll see if I can get that applied 
to my system to test.

**Comment by gbcox** [comment] 2021-01-03 21:29
New response from bugzilla: 1912046
```
Let me clarify:
- please ignore https://github.com/systemd/systemd/pull/17188. It was (mostly) reverted.
- https://github.com/keszybz/systemd/commit/a4ccce22d9552dc74b6916cc5ec57f2a0b686b4f makes systemctl
  ignore envvars that systemd doesn't like. This means that tools which call 'systemctl import-environment'
  will not fail.
  Other tools which call the DBus api directly need to do similar filtering.
- Lmod is not doing anything wrong. It is export bash functions as variables, which is a bit wonky, but allowed by POSIX.
  It actually makes sense for that use case.

So... if there's some particular tool which calls the Dbus api directly and tries to push unacceptable variables,
it needs to be patched not to do that. *Ideally* it would be patched to just push *only specific variables*,
because most variables only make sense for that program, for example $OLDPWD, $PWD, $SHLVL, $TERM, $SHELL.
Only variables that make sense *globally* for the user session should be pushed to the systemd environment block.

AFAIC, the issue has been resolved on the systemd side. The only thing that I plan to change (maybe)
is https://github.com/systemd/systemd/issues/4446. But it is not directly related to this issue.

```

**Comment by davidedmundson** [comment] 2021-01-03 22:13
Here is our client side filtering that you should have: https://invent.kde.org/plasma/plasma-workspace/-/blob/master/libkworkspace/updatelaunchenvjob.cpp#L139

One possible thing to note is I'm only validating the value against unapproved characters not the env name?

**Comment by gbcox** [comment] 2021-01-03 22:39
Yes, I have that file.  It is located in:  /usr/src/debug/plasma-workspace-5.20.4-1.fc33.x86_64/libkworkspace/

Can you possibly reply directly to the Fedora bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1912046
if you specific questions.  The folks on that bug are the systemd sme.

**Comment by gbcox** [comment] 2021-01-06 18:32
Here is a response from:  https://bugzilla.redhat.com/show_bug.cgi?id=1912046
In case you didn't see it.  

I pushed a pull request to beef up systemd's docs a bit: https://github.com/systemd/systemd/pull/18137.
It also deprecates a blanket 'systemctl import-environment' command and changes systemctl to emit
a warning when that is used.

It is fairly easy to describe how the environment is constructed by systemd, but the interaction
with other parts of the stack is complex and not documented well. I don't think the systemd
man pages are appropriate for this kind of documentation — we don't have the expertise and they
would become stale at some point. We could probably put a document under systemd.io if no better
place is found.

> To dig a bit further, the memo says "Define shell-specific setup through shell-specific profile scripts.",
> but systemd goes through the shell-specific profile scripts.

Systemd itself doesn't use the shell *at all*. This also means that it doesn't care about profile
scripts. Instead, various desktop environments execute in an environment where the shell profile
functions have been executed, and when they call 'import-environment' or the dbus-api equivalent
to propagate session-specific variables, various variables are pushed to the manager environment
block. I don't think this makes sense, because we end up with too many wrong things in the global
environment.

What I think should happen is that the desktop environment should export a few variables it
sets itself (emphasize *itself* here, if the desktop environment is assigning a variable, it knows
whether it belongs in the global session block): DESKTOP_SESSION, DISPLAY, GDMSESSION, GDM_LANG,
GNOME_SETUP_DISPLAY?, SESSION_MANAGER?, WAYLAND_DISPLAY, XAUTHORITY, XDG_SESSION_*, or equivalent
for other environments.

Whenever a shell process is created for the user, it should execute shell profile functions and
create set the shell-specific variables there.

I'm not an expert in bash profile initialization, but it seems that the right thing happens already:
when I clean up my systemd user environment block by removing e.g. all MODULE* variables, and
start a shell process as a service, I get them back:
$ systemd-run --user -t bash
(nested) $ set|grep ^MODULE
MODULEPATH=/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
MODULEPATH_modshare=/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1
MODULESHOME=/usr/share/Modules
MODULES_CMD=/usr/share/Modules/libexec/modulecmd.tcl
MODULES_RUN_QUARANTINE='LD_LIBRARY_PATH LD_PRELOAD'

When I start a gnome-terminal, the shell in the gnome terminal also has the MODULE* variables.
So it seems that the environment-modules stuff is properly initialized without pushing anything
through the manager environment block.
I don't think there's anything to fix in environment modules. It's gnome-desktop/kde that might
need some tweaking.

**Comment by davidedmundson** [comment] 2021-01-14 11:48
FYI, a patch merged into Plasma 5.21 that filters env names as well the env values. I'm hoping this fixes our issue.

**Closed by davidedmundson** 2021-01-14 11:48 UTC

**Comment by gbcox** [comment] 2021-01-14 20:49
> FYI, a patch merged into Plasma 5.21 that filters env names as well the env values. I'm hoping this fixes our issue.

Great news David!  Can you point me toward the patch so I can advise the Fedora maintainers and see if they can backport so we can test it out?  Also, I had opened https://bugzilla.redhat.com/show_bug.cgi?id=1912046 in Fedora to see if we could get the systemd and DE folks all on the same page to avoid this type of issue going forward.  Part of the systemd response to that bug was:  

```
What I think should happen is that the desktop environment should export a few variables it
sets itself (emphasize *itself* here, if the desktop environment is assigning a variable, it knows
whether it belongs in the global session block): DESKTOP_SESSION, DISPLAY, GDMSESSION, GDM_LANG,
GNOME_SETUP_DISPLAY?, SESSION_MANAGER?, WAYLAND_DISPLAY, XAUTHORITY, XDG_SESSION_*, or equivalent
for other environments.

Whenever a shell process is created for the user, it should execute shell profile functions and
create set the shell-specific variables there.
```
Is this the approach KDE is taking going forward or do you have a better idea or path?  You can either respond in the fedora bug or here and I'll pass the word along.  Fedora has made it a prioritized bug to attempt to ensure we have everyone's concurrence (as much as possible).   

Thanks again for your quick attention and action.  It is much appreciated!

**Comment by cocodrino** [comment] 2022-05-01 22:37
Hi, just for information, I'm using the latest version of KDE manjaro and tried to run wayland installing `plasma-wayland-session`as said in several forums, after select this in SDDM the loader screen is displayed but after that my screen is black and only shows the cursor...

following the steps of [torokati44](https://github.com/torokati44) seems work fine, the weird part is that I'm not using nvidia, amd or any dedicated GPU, my laptop is a carbon x1 with intel chip...

**Comment by Megalomaniak** [comment] 2022-09-11 16:42
Same issue, and I had not done anything to my KDE plasma configs or anything(no recent updates no nothing) it just suddenly decided to not start sessions anymore, login and the monitors turn off. Truly the year of Linux on the Desktop right here. Jokes aside...

 > @torokati44 said: Well, based on this, I just tried editing `/usr/share/wayland-sessions/plasmawayland.desktop`, replacing the `Exec=` line with:
`Exec=/usr/bin/dbus-run-session /usr/bin/startplasma-wayland` and not touching anything else. (Then I had to `sudo service sddm restart`, but simply rebooting would have been also fine most likely...)

This didn't work, at least not with a simple reboot.

> @torokati44 said: When switching to a textual console however (say, with Ctrl+Alt+F4), logging in there, then issuing `dbus-run-session startplasma-wayland`, Plasma loads and works just fine, on Wayland.

But at least this does.

> @cocodrino said: I'm using the latest version of KDE manjaro

Yep, same here. Latest stable, might have to switch over to testing I guess.

**Comment by rickythewoof** [comment] 2025-03-22 18:50
I know it's old, but also right now if installing KDE Plasma by following the official documentation and running `dnf install @kde-desktop-environment` it does that. By manually running `dbus-run-session startplasma-wayland` it works, so unfortunately this may mean that it's still not fixed
