### ISSUE TITLE
Dual monitors recognised as single giant screen

### ISSUE THREAD

**Issue by qjqqyy** [sddm/sddm#265] opened 2014-08-13 15:25 UTC
SDDMappears to not recognise the 2 physical Xmonitors and display things as if it is a single big screen.
The login prompt is placed right in the middle.
theme: breeze

**Comment by lnxslck** [comment] 2015-01-28 16:42
I use 2 monitors and i can't reproduce this bug. To me SDDM appears in 2 different monitors

**Comment by brenns10** [comment] 2015-01-28 17:01
I can reproduce it with the breeze login screen, but not with other login screens.  I'm thinking it might be an issue with that theme.

**Comment by lnxslck** [comment] 2015-01-29 13:52
@brenns10 I also have the breeze login screen

**Comment by tbleiker** [comment] 2015-02-10 17:21
Same here. With dual monitor and breeze theme, the login screen is placed in the middle of / between the two screens.

**Comment by ava1ar** [comment] 2015-03-11 01:07
Used to work good, but now also shows the login screen improperly. May be this is theme related, but not only breeze theme shows this weird behavior.

**Comment by Darktori** [comment] 2015-03-27 22:46
I also see the login screen right in the middle. Which is bad, because the other "screen" is my TV plugged in using HDMI, and always disabled in KDE settings when not used.

**Comment by eliasp** [comment] 2015-03-28 00:28
For me, the results vary wildly.
One time I get a clone on both screens, where the clone on the larger screen is a horribly scaled up version of the smaller screen.
Next time, it's a clone too, but this time with the proper size/resolution on the larger screen and the smaller screen showing the same picture, but with the not-fitting content moved off the screen.
And I don't know what kind of scenarios I've seen beyond that - I should probably start taking pictures whenever I reboot my laptop every 2 weeks or so ;)

**Comment by CommanderAlchemy** [comment] 2015-04-11 14:42
I'm also using breeze theme and the login screen creates one big across all my 3 screens. Then the splash screen happens individually on each screen stuttering when showing up and going away.

**Comment by flyingDavid** [comment] 2015-04-11 14:59
The issue with the breeze theme should be fixed in Plasma-workspace 5.3, there should be a login prompt on every screen.
See also: http://quickgit.kde.org/?p=plasma-workspace.git&a=commit&h=1985e8bf6bbc6044bd5ffac3c1b501536f2d1dd2

This workaround could be revoked as soon as sddm reaches version 1.0 and is widely spread.

**Comment by eliasp** [comment] 2015-04-12 17:43
Looks now like this here:
![sddm dual-screen, dual-panel :)](https://cloud.githubusercontent.com/assets/48491/7106740/1cf262f2-e14c-11e4-84fa-1bf5dc6a2dfb.jpg).

**Comment by flyingDavid** [comment] 2015-04-12 19:04
@eliasp : Which sddm version, which plasma-workspace version and which distro are you using?

**Comment by eliasp** [comment] 2015-04-13 05:19
@flyingDavid Latest sddm + Plasma 5 from git on top of Qt 5.4.1.
X.org is autoconfigured (primary screen is 1920x1080, secondary connected via DP is 2560x1440).

**Comment by flyingDavid** [comment] 2015-04-17 16:19
I submitted a patch which should fix your issue, can you rebuild and reinstall plasma-workspace and test it?

**Comment by plfiorini** [comment] 2015-08-17 21:13
This might be fixed now, could someone do some more test with the master branch and see if it's fixed?

**Comment by plfiorini** [comment] 2015-09-05 23:26
I'll leave this open for further testing but it will be moved to 0.13

**Comment by plfiorini** [comment] 2015-10-17 12:05
With #511 multiple screens should be good now, please reopen if you still see issues.

**Closed by plfiorini** 2015-10-17 12:05 UTC
Labels: bug, multi-monitor

**Comment by muesli** [comment] 2017-03-28 12:37
I'm seeing something rather similar with 0.14. Setup consists of three monitors, from left to right: 4k, 1080p, 1080p. The third monitor's view is displayed on the top-left of the primary 4k monitor, so I'm seeing two login screens on that monitor.
