### ISSUE TITLE
Wrong color and no login on secondary monitor

### ISSUE THREAD

**Issue by guiodic** [sddm/sddm#2000] opened 2024-10-15 11:32 UTC
With the upgrade to Qt 6.8 when sddm starts on a dual-monitor configuration, on the secondary monitor the colours of the pulsants restarts etc. are dark instead of light (maybe this is due to KDE?) but above all I cannot log in from the secondary monitor, but only from the main monitor (in my case the laptop)

**Comment by hirak99** [comment] 2024-10-15 13:07
Same problem. I'm using nVidia (RTX 3090) if that matters.

**Comment by hirak99** [comment] 2024-10-15 13:47
Coincidental (different) bug that started at the same time: https://bugs.kde.org/show_bug.cgi?id=494815

From the looks of it they seem unrelated, nonetheless specifying here just in case.

**Comment by FozzieHi** [comment] 2024-10-17 08:55
Same issue here, I'm also using an NVIDIA GPU, a 1060, if it helps.

**Comment by lluisfortes1** [comment] 2024-10-17 09:11
Same issue here.
It has been reported here too:
https://bugs.kde.org/show_bug.cgi?id=494804
https://bugs.kde.org/show_bug.cgi?id=494894

"After switching the SDDM theme from "Breeze" to "Maldives" the login worked again"

**Comment by twokilohertz** [comment] 2024-10-20 16:26
Same issue. My graphics card is an AMD RX 6700 XT, so it isn't just NVIDIA users. :)

Login prompt appears on both of my two monitors, however the main monitor is missing the shutdown, restart, etc. buttons and login doesn't work - however it all works on the secondary monitor.

**Comment by jurassicjordan** [comment] 2024-10-21 20:24
having same issue since updating yesterday, occurring on my RTX 3060, running endeavourOS. Login only occurs from the HDMI monitor, not the Displayport monitor. I thought Plasma was at fault at first, freaked me out.

**Comment by GithubUser5462** [comment] 2024-10-23 09:12
Having the same issue on EndeavourOS / Arch :
- a laptop with AMD Ryzen 7 PRO 6850U with Radeon Graphics
- a PC with Radeon 6700 XT

**Comment by FlailoftheLord** [comment] 2024-10-24 13:07
Same issue, secondary monitor is greyed out, I can enter my password into the login field but it does nothing.
can only login via the first monitor (they're both the exact same model and resolution) It only seems to be an issue when logging in  and not for unlocking a locked screen.

Kernel: Linux 6.11.5-arch1-1
CPU-AMD Ryzen 5800X
GPU-AMD Radeon RX 6700XT
Display (24G2W1G3-): 1920x1080 @ 144 Hz in 24" [External]
Display (24G2W1G4): 1920x1080 @ 144 Hz in 24" [External] *
Vulkan: 1.3.289 - radv [Mesa 24.2.5-arch1.1]
OpenGL: 4.6 (Compatibility Profile) Mesa 24.2.5-arch1.1
LM: sddm 0.21.0 (Wayland)
DE: KDE Plasma 6.2.2
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Breeze (Dark_modded) [Qt], Breeze-Dark [GTK2], Breeze [GTK3/4]

Edit: Issue fixed as of Plasma: 6.2.3 (arch 6.11.9)

**Comment by mrborghini** [comment] 2024-10-25 14:18
For me it's the other way around. I cannot login on my main monitor, but only my second monitor.

**Comment by Malinki03** [comment] 2024-10-25 18:52
Same issue here, can only login from my secondary monitor (which is connected by HDMI, while the main one is connected by DP and all options appear greyed out).

CPU: AMD Ryzen 5600X
GPU: Nvidia 3070ti (560.35.03 Driver).
Kernel: Linux 6.11.5-arch1-1
DE: KDE Plasma 6.2.2

**Comment by Vogtinator** [comment] 2024-10-25 20:00
FWICT this was either caused by Plasma 6.2.x or Qt 6.8.0. SDDM's own themes are not affected, so let's track this issue at https://bugs.kde.org/show_bug.cgi?id=494804.

**Closed as not planned by Vogtinator** 2024-10-25 20:00 UTC
