### ISSUE TITLE
keyboard layout selections don't work in SDDM with Wayland greeter

### ISSUE THREAD

**Issue by Conan-Kudo** [sddm/sddm#1528] opened 2022-03-09 19:32 UTC
_This was originally reported by @adamwill as ***[RHBZ#2062415](https://bugzilla.redhat.com/show_bug.cgi?id=2062415)***_

In Fedora 36 and Rawhide, whatever language/keyboard layout you select during installation, SDDM will show the selected keyboard layout as `af` when you boot up. This is Afrikaans, which AIUI is functionally very similar to the US English layout (I think it supports some additional characters with dead keys).

I tried to test what keyboard layout is *actually* being used. I did an install in UK English, with a user called `test` with password `test`. After install, I logged in, verified the UK English keyboard layout was being used in KDE, and changed the user's password to:

`weakpassword"`

Note that in the UK English keyboard layout, you type the `"` character with <kbd>shift</kbd>+<kbd>2</kbd>. On US English and similar layouts, you type it with <kbd>shift</kbd>+<kbd>'</kbd>, where <kbd>'</kbd> is the key to the left of <kbd>Enter</kbd>. On a US English keyboard, <kbd>shift</kbd>+<kbd>2</kbd> gives the character `@`.

So, if the keyboard layout in use is UK English, I should be able to log in by typing <kbd>shift</kbd>+<kbd>2</kbd>; if it's US English or similar I should type <kbd>shift</kbd>+<kbd>'</kbd>.

If I leave the layout selector in SDDM at `af`, I can log in by typing <kbd>shift</kbd>+<kbd>'</kbd>, which is consistent with the layout being `af` or `us`.

If I change the layout selector in SDDM to `gb`, which should give me a UK English layout, I cannot log in by typing <kbd>shift</kbd>+<kbd>2</kbd> as expected. I still have to type <kbd>shift</kbd>+<kbd>'</kbd>. So it seems like changing the layout does not work.

Executive summary: keyboard layouts in SDDM are just hosed. I think it's either always using `af` or always using `us`, and selecting layouts just does not work. I wonder if this has never actually been hooked up to work properly on Wayland?

In KDE itself, this does work properly. The UK layout is used by default as expected.

**Comment by Conan-Kudo** [comment] 2022-03-09 19:33
This is considered a blocker bug for Fedora Linux 36 release, so it'd be appreciated if someone could help here.

**Comment by Conan-Kudo** [comment] 2022-03-09 19:38
Also another note: this is using SDDM Wayland with KWin as the compositor, using the configuration provided in plasma-workspace in Plasma 5.24.2.

**Comment by marcdeop** [comment] 2022-03-13 13:45
it would be interesting to know if the layout change doesn't work at all or if it changes to a wrong layout. The implications might be different

**Comment by davidedmundson** [comment] 2022-03-13 14:50
>This is considered a blocker bug for Fedora Linux 36 release,

Run the X greeter then

**Comment by Conan-Kudo** [comment] 2022-03-13 15:25
@davidedmundson I've posited the question in the Fedora KDE SIG issue tracker: [pagureio#fedora-kde/SIG#183](https://pagure.io/fedora-kde/SIG/issue/183). If you want to give feedback there, feel free.

**Comment by aleixpol** [comment] 2022-03-13 23:21
> it would be interesting to know if the layout change doesn't work at all or if it changes to a wrong layout. The implications might be different

It is not implemented for Wayland, it's also not standardised in there as random clients don't have the power to switch the keyboard layout. In Plasma we implement this using dbus through org.kde.KeyboardLayouts.

**Comment by j5k** [comment] 2022-03-16 19:28
I can confirm this issue. If I switch to wayland according to [https://wiki.archlinux.org/title/SDDM#Running_under_Wayland](https://wiki.archlinux.org/title/SDDM#Running_under_Wayland) and `sddm-git` with version `0.19.0.137.gc257a40` the keyboard layout is set to 'af' (afrikaans) and you can not change this, since no dropdown menu is visible after clicking on it. The same for the session chooser (X11 or Wayland).

**Comment by AdamWill** [comment] 2022-03-16 20:23
We have the visual glitches with the menus fixed on Fedora, so you can use the dropdown menu there, but selecting another choice doesn't actually seem to *work*, as described in the initial post.

**Comment by bam80** [comment] 2022-04-27 15:18
> In Plasma we implement this using dbus through org.kde.KeyboardLayouts.

Maybe we could implement this dbus interface in SDDM?
Hypothetically it would allow us to use the same QML component for switching layouts.

EDIT:
as long as we use Weston(or something beside KWin) it might be problematic as there is no standard interface for compositors to change the layouts indeed

**Comment by bam80** [comment] 2022-04-27 20:42
The other thing we could possibly do to address this and other potential problems is to optionally use Qt GLFS backend directly thus eliminating the need of communicating with compositors entirely:
https://doc.qt.io/qt-5/embedded-linux.html

**Comment by mcloaked** [comment] 2022-04-28 19:46
Can someone tell me what the line should for the setting to change the keyboard layout in the sddm config files please - I need the gb keyboard layout otherwise entering various characters for passwords to login is awkward as has been pointed out, since the default keyboard layout is us.  Also I am testing on a laptop and the touchpad tap to click is off by default, so the pull down sddm greeter for keyboard layout is not accessible - previously running under xorg the settings for both touchpad and keyboard layout could be defined in the xorg config files for libinput.

**Comment by gene-git** [comment] 2022-04-28 20:15
i know this thread is about dynamic changes but would it help to 
(i) change sddm config to use weston --config <file> where the weston config file  has the keyboard, touch-pad etc set as desired?
(ii)   Maybe  kwin_wayland has something similar but I couldnt find a way to pass the info via command line or environment - is it doable? 

not yet tested.

**Comment by mcloaked** [comment] 2022-04-28 20:54
I tried this - and despite the config set to use a 'gb' keyboard layout sddm greeter does not honour it and the keyboard layout remains 'us'.  Also setting the libinput section to turn on tap-to-click, that is also not honoured by sddm either.

**Comment by bam80** [comment] 2022-04-28 23:37
> (ii) Maybe kwin_wayland has something similar but I couldnt find a way to pass the info via command line or environment - is it doable?

KWin respects [org.freedesktop.locale1](https://www.freedesktop.org/software/systemd/man/org.freedesktop.locale1.html) D-Bus interface on start, you can try [localectl](https://www.freedesktop.org/software/systemd/man/localectl.html#) to set the layout(s) before:
https://lxr.kde.org/source/plasma/plasma-workspace/startkde/startplasma-wayland.cpp#0031
https://lxr.kde.org/source/plasma/kwin/src/xkb.cpp#0161

Note:
[KWIN_XKB_DEFAULT_KEYMAP](https://lxr.kde.org/source/plasma/kwin/src/xkb.cpp#0137) env var needs to be set first so the changes are not overridden from  `~/.config/kxkbrc`

**Comment by mcloaked** [comment] 2022-04-29 10:39
I already have: $ localectl status
   System Locale: LANG=en_GB.UTF-8
       VC Keymap: uk
      X11 Layout: n/a
So that didn't seem to help.  

Also the contents of this file already have the gb in it:

$ cat ~/.config/kxkbrc
[$Version]
update_info=kxkb_variants.upd:split-variants,kxkb.upd:remove-empty-lists,kxkb.upd:add-back-resetoptions

[Layout]
DisplayNames=
LayoutList=gb
LayoutLoopCount=-1
Model=pc101
Options=caps:none,altwin:menu_win
ResetOldOptions=true
ShowFlag=false
ShowLabel=true
ShowLayoutIndicator=true
ShowSingle=false
SwitchMode=Global
Use=true
VariantList=

**Comment by bam80** [comment] 2022-04-29 10:42
@mcloaked `X11 Layout` is essential, seem you don't have it configured.
Here is mine:
```
$ localectl 
   System Locale: LANG=ru_RU.UTF-8
                  LANGUAGE=ru:en_US:en
       VC Keymap: us
      X11 Layout: us,ru
       X11 Model: pc105
     X11 Variant: ,
     X11 Options: grp_led:scroll

**Comment by gene-git** [comment] 2022-04-29 10:42
never mind -that changes the system settings

**Comment by mcloaked** [comment] 2022-04-29 10:48
OK - I will try that adding in the X11 Layout - though it is strange that the X11 layout should be needed when running purely in Wayland. Also is there a way to get touchpad tapping working if sddm is running in wayland?

**Comment by bam80** [comment] 2022-04-29 10:53
> it is strange that the X11 layout should be needed when running purely in Wayland

It's not as long as you have proper ~/.config/kxkbrc, just something to try (and don't forget [KWIN_XKB_DEFAULT_KEYMAP](https://lxr.kde.org/source/plasma/kwin/src/xkb.cpp#0137) env var).
Are you sure the actual layout is not `gb` when you typing?


> Also is there a way to get touchpad tapping working if sddm is running in wayland?

That one I'm not aware of, sorry.

**Comment by mcloaked** [comment] 2022-04-29 12:59
Where is the best place to set the environment variable KWIN_XKB_DEFAULT_KEYMAP   - /etc/environment ?

**Comment by mcloaked** [comment] 2022-04-29 13:23
I have in sddm.conf

[General]
#------
#..sddm on wayland
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell,KWIN_XKB_DEFAULT_KEYMAP=gb

#------
InputMethod=
Numlock=none

[Wayland]
#------
#..sddm on wayland
#..this may not be needed -
CompositorCommand=kwin_wayland --no-lockscreen
#------
EnableHiDPI=true
SessionCommand=/usr/share/sddm/scripts/wayland-session
SessionDir=/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log

The greeter looks OK  but the keyboard still has not become gb (UK).

So that variable is not set.

[mike@lenovo2 ~]$ printenv | egrep KWIN_XKB_DEFAULT_KEYMAP
[mike@lenovo2 ~]$

and

[mike@lenovo2 ~]$ sudo localectl status
   System Locale: LANG=en_GB.UTF-8
       VC Keymap: uk
      X11 Layout: gb
[mike@lenovo2 ~]$

So the question remains as to how to set that environment variable so that sddm knows about it......

**Comment by mcloaked** [comment] 2022-04-29 16:42
After working with another user testing the sddm wayland set up, he suggested a change to the sddm.conf file to use the following:

[General]
#------
#..sddm on wayland
DisplayServer=wayland
#GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
#GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell,KWIN_XKB_DEFAULT_KEYMAP=gb
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell,XKB_DEFAULT_LAYOUT=gb
#------
InputMethod=
Numlock=none

i.e. replacing  WIN_XKB_DEFAULT_KEYMAP=gb with XKB_DEFAULT_LAYOUT=gb and now the sddm greeter accepts passwords including some of the characters that are not letters or numbers using the correct keystroke combinations for a UK gb keyboard.  So that one change alone was the key to making it work,  

So now hopefully there will be a way to also set touchpad tap-to-click to have full sddm wayland functionality for the greeter.

**Comment by bam80** [comment] 2022-04-29 17:01
Congrats!
Seem I have explanation now why it didn't work - you used `kwin_wayland` alone and the `org.freedesktop.locale1` functionality is in `startplasma-wayland` binary which you didn't use :)

The only part remaining unclear to me is why it doesn't work out of box just with proper `kxkbrc` config you have..

**Comment by gene-git** [comment] 2022-04-29 17:06
@bam80 do you know if kwin_wayland has similar env overirdes for Libinput - in partcular for tap to click?

**Comment by bam80** [comment] 2022-04-29 17:16
Sorry, no. It might be similar problem if kwin alone can't read configs for some reason.
Anyway, you can report it for kwin on KDE bugtracker, I think (and paste the link here).

**Comment by bam80** [comment] 2022-09-08 11:38
https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2088

**Comment by notorand-it** [comment] 2022-09-13 07:08
That layout dropdown in pretty useless at least in Wayland (with default theme).
1. It is clipped to the bottom screen limit (I can only see from "af" to "em");
2. It is not scrollable but I see I can go down with the arrow key but have no idea which item is selected;
3. It doesn't search by typing, so typing "i" or  "f" doesn't select the first item whose name starts with that letter;
4. It seems it cannot be disabled.

I am willing to help here with logs and details, but don't know how to.
Distribution: ArchLinux
Kernel Version : 5.19.7.zen2-1
Plasma Version : 5.25.5-2
KDE Version : 22.08.1-1
Frameworks Version : 5.98.0-1
Qt5 Version : 5.15.6+kde+r4-1
Wayland Version : 1.21.0-1

**Closed as completed** 2022-11-11 16:09 UTC

**Comment by aufkrawall** [comment] 2023-06-23 18:50
I'm affected by this too (0.20 release): Wayland greeter with kwin ignores de keyboard mapping, but works with Xorg. Double-checked everything (I think) and no workaround works. Then I saw this recent kwin commit that sounds like there is a good chance it could fix it:
https://invent.kde.org/plasma/kwin/-/commit/f70bda9f6de2d38ae3859afb3f96cad1e9c47590

Will report back once a release build with it is shipped.

**Comment by Vogtinator** [comment] 2023-06-24 10:14
That was actually discussed in https://github.com/sddm/sddm/issues/1735

**Comment by aufkrawall** [comment] 2023-06-24 10:53
Thanks!
So the fix is required + starting kwin via `kwin_wayland --locale1`?

**Comment by Vogtinator** [comment] 2023-06-24 11:15
Yes.
