### ISSUE TITLE
no cursor in password area sddm 0.14.0-2. 

### ISSUE THREAD

**Issue by hikikomori4** [sddm/sddm#825] opened 2017-06-06 20:47 UTC
sorry i dont speak english.=(

Wrong geometry of two screens system sddm:
https://i.stack.imgur.com/1JOuU.jpg

No have keyboard input and cursor in password area until i move mouse.
Login by keyboard is impossible!
When move mouse - cursor make vissible and i can login.

My Cfg:
Manjaro KDE Edition 64x 17.0.1, 17.0.2-pre4. 
mITX Asus P8H61-I rev3.0 
 xrandr --output HDMI1 --mode 1280x1024 --rate 60.02 --output VGA1 --mode 1680x1050 --rate 60.02

**Comment by Pointedstick** [comment] 2020-11-29 01:19
Duplicate of https://github.com/sddm/sddm/issues/755

**Closed by Pointedstick** 2020-11-29 01:19 UTC
