### ISSUE TITLE
blackscreen since systemd update

### ISSUE THREAD

**Issue by edpil02** [sddm/sddm#1190] opened 2019-08-17 12:56 UTC
My distro update to systemd-243~rc1-2.fc31 , since sddm fail  to start.
No crash, no systemctl errors , no sddm logs  but only  /var/run/sddm/ * no autorization or missing file  in xorg.log, and  sddm.service  stay active.
 
After some tests found that ssdm start only if i put  the nvidia modules  in  initramfs.

This issue is due to a change in systemd because downgrade solve the problem.
Some services seems to be changed.

Filed a bug report to systemd upstream; they  said :
 " this is not actionable to us. Please provide a full log excerpt of anything around the issue, 
otherwise there's little we can do."

**Comment by alexws54tk** [comment] 2019-09-02 07:46
Same too.
Blank screen with cursor, but no greeter shows
In `/var/log/Xorg.0.log` one error `(EE) Failed to open authorization file "/var/run/sddm/{***}": No such file or directory`, but file is in own place.

**Comment by I-Al-Istannen** [comment] 2019-09-10 14:58
I have the same issue. Switching to another TTY and running `systemctl restart sddm.service` fixes the issue and causes sddm to show up.

It also works on `linux`, just `linux-lts` is broken since the last lts update (I assume, I ran a system update this morning. Might have also updated systemd or the firmware.)

**Comment by AnonFuncsAreAwesome** [comment] 2019-09-14 15:53
Got the same problem after systemd update as well, although I'm on amdgpu.
Happens for me on both linux-lts and mainline.

systemd 243.0
sddm 0.18.1

**Comment by dashingderpderp** [comment] 2019-09-26 13:38
I think it's a race condition and depends on the services you have set with systemd as well. I was able to get rid of issue by disabling docker, but you could try removing or adding services and issue might go away. Comparing journald logs locally between working and failing case, I see that SeatManager::createSeat never gets called when the issue happens.

**Comment by dashingderpderp** [comment] 2019-10-20 15:28
The issue is that in LogindSeat::LogindSeat, SDDM checks for "CanGraphical" property of logind just once and only initializes if it's set to true. This is not the case if logind initializes before the graphics driver does, which is what's happening in all the failing cases for me. SDDM should really be instead watching "CanGraphical" continuously and take further action once it's changed to true.

**Comment by dashingderpderp** [comment] 2019-10-27 18:57
Hi all, this issue is fixed with the fix for [systemd/issues/13296](https://github.com/systemd/systemd/issues/13296). Feel free to close this issue.

**Comment by davidedmundson** [comment] 2019-10-27 21:17
Thanks!

**Closed by davidedmundson** 2019-10-27 21:17 UTC
