### ISSUE TITLE
sddm 0.13.0 crashes in Arch linux

### ISSUE THREAD

**Issue by poidl** [sddm/sddm#556] opened 2015-11-15 00:46 UTC
Hi, I updated my Arch packages today and sddm crashes. The same issue was reported in Arch [bugtracker](https://bugs.archlinux.org/task/47062). Thanks, Stefan

**Comment by poidl** [comment] 2015-11-15 01:12
Sorry please disregard this. I just re-built 0.13.0 from Arch's ABS, and it works fine now.

**Comment by poidl** [comment] 2015-11-15 01:44
I realized now that the bug went away because I set the cmake build config to "DCMAKE_BUILD_TYPE=Debug". When I use "Release", the bug reappears. Trace attached. Related to #540 ?
 
[trace.txt](https://github.com/sddm/sddm/files/34790/trace.txt)

**Comment by Zeitwaechter** [comment] 2015-11-18 18:30
I did have a similiar problem.
Even though the problem stated was that X could not be started / the monitor could not be found.
Cinnamon had problems aswell. Plasma itself still worked out of the box.
Might be part of an xorg-server issue in my case.
..
As beginner I rsync'd my recently made backup.. works now again.

**Comment by Zeitwaechter** [comment] 2015-12-15 00:22
It's like this, though my feedback still won't help you in any case - but chances are that it's not important anymore:

I retried the newest version to check out if there was still the problem with crashing while booting Arch up.
But whatever you did, you fixed the problem already: After changing to sddm-git (via yaourt) it booted up all normal again.

Maybe you want to release a new version of sddm with it's current state of the art soon for the others?

Greetings :)

**Comment by sinkuu** [comment] 2015-12-27 23:53
I'm using sddm-git(0.13.0.25.g56f6417-1), and still sometimes get segfaults when I login.

System log:
```
12月 28 08:37:16 mylaptop sddm-greeter[563]: QObject: Cannot create children for a parent that is in a different thread.
                                             (Parent is SDDM::GreeterApp(0x7ffd8012df00), parent's thread is QThread(0x1e02920), current thread is QThread(0x1e55050)
12月 28 08:37:16 mylaptop sddm-greeter[563]: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
12月 28 08:37:16 mylaptop sddm-greeter[563]: file:///usr/share/sddm/themes/breeze/components/InfoPane.qml:52:22: Unable to assign [undefined] to int
12月 28 08:37:16 mylaptop sddm-greeter[563]: Adding view for "LVDS1" QRect(0,0 1366x768)
12月 28 08:37:16 mylaptop sddm-greeter[563]: file:///usr/share/sddm/themes/breeze/components/InfoPane.qml:52:22: Unable to assign [undefined] to int
12月 28 08:37:16 mylaptop sddm-greeter[563]: Adding view for "VGA1" QRect(0,0 1600x900)
12月 28 08:37:16 mylaptop sddm-greeter[563]: Message received from daemon: Capabilities
12月 28 08:37:16 mylaptop sddm-greeter[563]: Message received from daemon: HostName
12月 28 08:37:17 mylaptop systemd-coredump[530]: Process 471 (sddm-greeter) of user 995 dumped core.
                                                 
                                                 Stack trace of thread 471:
                                                 #0  0x00007f5c6a984c0f n/a (libKF5CoreAddons.so.5)
                                                 #1  0x00007f5c6a9850df _ZN9KDirWatchD1Ev (libKF5CoreAddons.so.5)
                                                 #2  0x00007f5c6a9850f9 n/a (libKF5CoreAddons.so.5)
                                                 #3  0x00007f5c7eb53f88 __run_exit_handlers (libc.so.6)
                                                 #4  0x00007f5c7eb53fd5 exit (libc.so.6)
                                                 #5  0x00007f5c78c4d6f5 _XDefaultIOError (libX11.so.6)
                                                 #6  0x00007f5c80c73c5e n/a (libQt5XcbQpa.so.5)
                                                 #7  0x00007f5c78c4d91e _XIOError (libX11.so.6)
                                                 #8  0x00007f5c78c4b9fb _XReply (libX11.so.6)
                                                 #9  0x00007f5c78c4711d XSync (libX11.so.6)
                                                 #10 0x00007f5c7c9a4038 n/a (libGL.so.1)
                                                 #11 0x00007f5c7c9a4ed3 n/a (libGL.so.1)
                                                 #12 0x00007f5c7c97ee19 n/a (libGL.so.1)
                                                 #13 0x00007f5c80e1d134 n/a (libqxcb-glx-integration.so)
                                                 #14 0x00007f5c80e1d159 n/a (libqxcb-glx-integration.so)
                                                 #15 0x00007f5c7ffae09d _ZN17QOffscreenSurface7destroyEv (libQt5Gui.so.5)
                                                 #16 0x00007f5c7ffae121 _ZN17QOffscreenSurfaceD1Ev (libQt5Gui.so.5)
                                                 #17 0x00007f5c7ffae159 _ZN17QOffscreenSurfaceD0Ev (libQt5Gui.so.5)
                                                 #18 0x00007f5c8056248c n/a (libQt5Quick.so.5)
                                                 #19 0x00007f5c80562da1 _ZN13QSGRenderLoop7cleanupEv (libQt5Quick.so.5)
                                                 #20 0x00007f5c7f6dfad1 _Z21qt_call_post_routinesv (libQt5Core.so.5)
                                                 #21 0x00007f5c7f6e03d2 _ZN16QCoreApplicationD1Ev (libQt5Core.so.5)
                                                 #22 0x00000000004148b5 main (sddm-greeter)
                                                 #23 0x00007f5c7eb3e610 __libc_start_main (libc.so.6)
                                                 #24 0x0000000000414989 _start (sddm-greeter)
                                                 
                                                 Stack trace of thread 519:
                                                 #0  0x00007f5c7ebfe18d poll (libc.so.6)
                                                 #1  0x00007f5c7b32bfbc n/a (libglib-2.0.so.0)
                                                 #2  0x00007f5c7b32c0cc g_main_context_iteration (libglib-2.0.so.0)
                                                 #3  0x00007f5c7f73754f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                 #4  0x00007f5c7f6de57a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                 #5  0x00007f5c7f4fabe4 _ZN7QThread4execEv (libQt5Core.so.5)
                                                 #6  0x00007f5c7fd5f055 n/a (libQt5Qml.so.5)
                                                 #7  0x00007f5c7f4ffb8e n/a (libQt5Core.so.5)
                                                 #8  0x00007f5c7d2af4a4 start_thread (libpthread.so.0)
                                                 #9  0x00007f5c7ec0713d __clone (libc.so.6)
                                                 
                                                 Stack trace of thread 474:
                                                 #0  0x00007f5c7ebfe18d poll (libc.so.6)
                                                 #1  0x00007f5c7b32bfbc n/a (libglib-2.0.so.0)
                                                 #2  0x00007f5c7b32c0cc g_main_context_iteration (libglib-2.0.so.0)
                                                 #3  0x00007f5c7f73754f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                 #4  0x00007f5c7f6de57a _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                 #5  0x00007f5c7f4fabe4 _ZN7QThread4execEv (libQt5Core.so.5)
                                                 #6  0x00007f5c7fd5f055 n/a (libQt5Qml.so.5)
                                                 #7  0x00007f5c7f4ffb8e n/a (libQt5Core.so.5)
                                                 #8  0x00007f5c7d2af4a4 start_thread (libpthread.so.0)
                                                 #9  0x00007f5c7ec0713d __clone (libc.so.6)
```

**Comment by dsteinborn** [comment] 2016-01-11 18:53
Also crashing with segfault on my archlinux installation with 0.13.0-2 installed.
I generated a config file as described in the [documentation](https://wiki.archlinux.org/index.php/SDDM#Configuration) using `sddm --example-config > /etc/sddm.conf` then modified `#HideShells=` to `HideShells=/sbin/nologin,/bin/false` and rebooted. It results in a segfault. Commenting the line with the `HideShells` configuration allows normal startup.

Just tried `HideShells=/bin/false` and `HideShells=/sbin/nologin` which don't result in a segfault when using `sddm --test-mode` whereas `HideShells=/sbin/nologin,/bin/false` also crashes in test-mode.

Messages from dmesg:
```
[    7.072230] sddm[642]: segfault at 3bf1b8c ip 00007f43b6e867ed sp 00007ffe435f2b90 error 4 in libQt5Core.so.5.5.1[7f43b6d44000+4c3000]
[    7.254723] sddm[683]: segfault at 3337b8c ip 00007fad793517ed sp 00007ffc183ff650 error 4 in libQt5Core.so.5.5.1[7fad7920f000+4c3000]
[    7.499193] sddm[729]: segfault at 2429b8c ip 00007fceab7877ed sp 00007ffe2c2287e0 error 4 in libQt5Core.so.5.5.1[7fceab645000+4c3000]
[    7.657806] sddm[764]: segfault at 2f77b8c ip 00007f8f0c49e7ed sp 00007ffdfec9df90 error 4 in libQt5Core.so.5.5.1[7f8f0c35c000+4c3000]
[    8.046712] sddm[864]: segfault at 3aabb8c ip 00007fd10b4d97ed sp 00007ffdba9e2b20 error 4 in libQt5Core.so.5.5.1[7fd10b397000+4c3000]
[  385.176101] sddm[1851]: segfault at 1f8bb8c ip 00007ff59bd327ed sp 00007ffdeb05c960 error 4 in libQt5Core.so.5.5.1[7ff59bbf0000+4c3000]
[ 2465.118571] sddm[3610]: segfault at 2bfdb8c ip 00007f840b0157ed sp 00007ffd4b254130 error 4 in libQt5Core.so.5.5.1[7f840aed3000+4c3000]
[ 2632.228621] sddm[3645]: segfault at 160bb8c ip 00007f362cf017ed sp 00007ffde8298500 error 4 in libQt5Core.so.5.5.1[7f362cdbf000+4c3000]
[ 2735.944277] sddm[3666]: segfault at 3fd3b8c ip 00007f41b90df7ed sp 00007ffe2ff4e2a0 error 4 in libQt5Core.so.5.5.1[7f41b8f9d000+4c3000]
[ 2744.554051] sddm[3668]: segfault at 15f3b8c ip 00007f37c726b7ed sp 00007ffdad886b10 error 4 in libQt5Core.so.5.5.1[7f37c7129000+4c3000]
[ 2754.546496] sddm[3670]: segfault at 144bb8c ip 00007f1d13a917ed sp 00007ffe7e1066a0 error 4 in libQt5Core.so.5.5.1[7f1d1394f000+4c3000]
[ 2853.836358] sddm[3697]: segfault at 259bb8c ip 00007f80cdf217ed sp 00007ffc8ecb02a0 error 4 in libQt5Core.so.5.5.1[7f80cdddf000+4c3000]
[ 3053.798902] sddm[3997]: segfault at 4a27b8c ip 00007fa6e7d837ed sp 00007ffc92f69170 error 4 in libQt5Core.so.5.5.1[7fa6e7c41000+4c3000]
```

Messages from journalctl:
```
Jan 11 18:07:40 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Service hold-off time over, scheduling restart.
Jan 11 18:07:40 hostname systemd[1]: Stopped Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:41 hostname systemd-coredump[645]: Process 642 (sddm) of user 0 dumped core.
                                                
                                                Stack trace of thread 642:
                                                #0  0x00007f43b6e867ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                                #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                                #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                                #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                                #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                                #5  0x000000000041a410 n/a (sddm)
-- Logs begin at Mo 2015-03-23 22:22:53 CET, end at Mo 2016-01-11 19:00:02 CET. --
Jan 11 18:07:40 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Service hold-off time over, scheduling restart.
Jan 11 18:07:40 hostname systemd[1]: Stopped Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:40 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:41 hostname systemd-coredump[645]: Process 642 (sddm) of user 0 dumped core.
                                                
                                                Stack trace of thread 642:
                                                #0  0x00007f43b6e867ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                                #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                                #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                                #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                                #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                                #5  0x000000000041a410 n/a (sddm)
                                                #6  0x000000000045623d __libc_csu_init (sddm)
                                                #7  0x00007f43b642859f __libc_start_main (libc.so.6)
                                                #8  0x000000000041aa69 _start (sddm)
Jan 11 18:07:41 hostname systemd-coredump[685]: Process 683 (sddm) of user 0 dumped core.
                                                
                                                Stack trace of thread 683:
                                                #0  0x00007fad793517ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                                #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                                #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                                #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                                #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                                #5  0x000000000041a410 n/a (sddm)
                                                #6  0x000000000045623d __libc_csu_init (sddm)
                                                #7  0x00007fad788f359f __libc_start_main (libc.so.6)
                                                #8  0x000000000041aa69 _start (sddm)
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Service hold-off time over, scheduling restart.
Jan 11 18:07:41 hostname systemd[1]: Stopped Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Service hold-off time over, scheduling restart.
Jan 11 18:07:41 hostname systemd[1]: Stopped Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Unit entered failed state.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Failed with result 'core-dump'.
Jan 11 18:07:41 hostname systemd-coredump[731]: Process 729 (sddm) of user 0 dumped core.
                                                
                                                Stack trace of thread 729:
                                                #0  0x00007fceab7877ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                                #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                                #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                                #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                                #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                                #5  0x000000000041a410 n/a (sddm)
                                                #6  0x000000000045623d __libc_csu_init (sddm)
                                                #7  0x00007fceaad2959f __libc_start_main (libc.so.6)
                                                #8  0x000000000041aa69 _start (sddm)
Jan 11 18:07:41 hostname systemd-coredump[765]: Process 764 (sddm) of user 0 dumped core.
                                                
                                                Stack trace of thread 764:
                                                #0  0x00007f8f0c49e7ed _ZNK10QStringRef7trimmedEv (libQt5Core.so.5)
                                                #1  0x0000000000428b28 _ZrsR11QTextStreamR11QStringList (sddm)
                                                #2  0x000000000042535a _ZN4SDDM11ConfigEntryI11QStringListE8setValueERK7QString (sddm)
                                                #3  0x000000000042a18d _ZN4SDDM10ConfigBase4loadEv (sddm)
                                                #4  0x0000000000423bd7 _ZN4SDDM10MainConfigC1Ev (sddm)
                                                #5  0x000000000041a410 n/a (sddm)
                                                #6  0x000000000045623d __libc_csu_init (sddm)
                                                #7  0x00007f8f0ba4059f __libc_start_main (libc.so.6)
                                                #8  0x000000000041aa69 _start (sddm)
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Service hold-off time over, scheduling restart.
Jan 11 18:07:41 hostname systemd[1]: Stopped Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: Started Simple Desktop Display Manager.
Jan 11 18:07:41 hostname systemd[1]: sddm.service: Main process exited, code=dumped, status=11/SEGV
```

**Comment by poidl** [comment] 2016-01-11 21:27
This sounds very similar to my problem, I have stuff like "QStringRef::trimmed" showing up in the trace. I confirm that displaying all users in the greeter solves the problem.

**Comment by dyrverE** [comment] 2016-02-08 11:32
Check which version of llvm-libs your mesa and/or sddm was built towards and make sure it's the same. needed llvm35-libs for building UE4Editor, turns out mesa did not like that at all and this resulted in segfaults in the greeter.

**Comment by plfiorini** [comment] 2016-08-23 19:17
This should be fixed now, that QStringRef::trimmed reminds me the problem with giving lists to settings such as HideShells and I cannot reproduce with git master.

Since we are good to go for 0.14.0 (I'm just waiting for someone to do more tests) I will close the issue. Feel free to reopen if you have the same problems when 0.14.0 comes out.

**Closed by plfiorini** 2016-08-23 19:17 UTC
Labels: crash/whitescreen
