### ISSUE TITLE
Laptop repeatedly goes to sleep when the lid is closed

### ISSUE THREAD

**Issue by roundoutandabout** [sddm/sddm#1362] opened 2021-01-26 21:15 UTC
I have a laptop with a second monitor connected, which I use as primary.

The problem is, when the lid is closed, the laptop goes to sleep shortly after login screen appears. I can wake it from sleep. But shortly after it goes to sleep again, even if I'm in the middle of typing the password.

The problem appears only during first boot.

### Expected behavior: 
Laptop doesn't go to sleep on the login screen during typing the password when the lid is closed.

### Actual behavior: 
Laptop goes to sleep even during typing the password.

### Steps to reproduce: 
1. Power on the laptop. 
2. Close the lid. 
3. Wait until the login screen appears.
4. Watch the laptop go to sleep after ~5 seconds

### Client configuration
**SDDM version:** 0.18.1
**Operating system:** KDE neon 5.20
**Hardware:** Intel + NVIDIA graphics

**Comment by nursoda** [comment] 2021-01-27 22:16
Duplicate of https://github.com/sddm/sddm/issues/1148?

**Comment by roundoutandabout** [comment] 2021-01-28 21:29
Yes, seems like it's the same issue
Uncommenting the line `HandleLidSwitchExternalPower=ignore` in `/etc/systemd/logind.conf` did the trick. 
Thanks @nursoda !

**Closed** 2021-01-28 21:30 UTC
