### ISSUE TITLE
Keyboard and mouse do not work after reboot for about 30 seconds

### ISSUE THREAD

**Issue by DrDoctor13** [sddm/sddm#895] opened 2017-09-23 02:58 UTC
When rebooting or booting into Linux (dual-boot), my keyboard will not input anything and neither will my mouse. This lasts for roughly 25-30 seconds then it starts working.

**Comment by Xwang1976** [comment] 2017-10-22 10:25
Something similar happens to me, but if I click on the password field, insert the password and press return, it logins even if nothing has been displayed when typing.

**Comment by adocampo** [comment] 2017-11-23 10:10
It happens also to me with Maui theme, but breeze works just fine. Try it.

**Comment by Pointedstick** [comment] 2020-11-29 01:19
Duplicate of https://github.com/sddm/sddm/issues/836

**Closed by Pointedstick** 2020-11-29 01:19 UTC
