### ISSUE TITLE
Software Keyboard

### ISSUE THREAD

**Issue by breenjoe** [sddm/sddm#1309] opened 2020-10-26 16:10 UTC
I'm running Manjaro with SDDM.  I only have a touchscreen interface.  When I am prompted for a password I cannot enter anything because there is no software keyboard visible.  Not sure if this is a bug but if a software keyboard does exist for SDDM it doesn't seem to be available before login to allow entering a password.

Additionally, by adding a virtual/software keyboard manually (e.g. qt5 keyboard) I can then see the keyboard but there are two issues.

1. tapping into the password text box brings up the virtual keyboard over the password box but when typing, no characters appear in the password text box so unable to login.
2. after 1. above the virtual keyboard disappears and if I then tap back into the password text box a tiny virtual keyboard appears that is not possible to correctly tap on the letters because they are too small.

**Comment by Pointedstick** [comment] 2020-11-29 01:22
Duplicate of https://github.com/sddm/sddm/issues/100

**Closed by Pointedstick** 2020-11-29 01:22 UTC
