### ISSUE TITLE
Setting DPI when using Wayland

### ISSUE THREAD

**Issue by ctron** [sddm/sddm#1709] opened 2023-04-19 07:02 UTC
After the upgrade to Fedora 38, it looks like SDDM is running with Wayland.

However, all questions asking for SDDM to scale, get answered with a snippet like this:

```
[X11]
ServerArguments=-dpi 192
```

Which seems to configure X11, which of course won't work with Wayland.

So, what is the proper replacement for this when using Wayland? Because right now, the login screen is super tiny on a 4k screen.

**Comment by piotr-dobrogost** [comment] 2023-04-19 08:15
Duplicate of issue #1704

**Closed as not planned** 2023-04-19 08:16 UTC
