### ISSUE TITLE
Changing expired password

### ISSUE THREAD

**Issue by kobaltd** [sddm/sddm#1601] opened 2022-10-22 21:56 UTC
When is this functionality implemented? Without it, it is not possible to use the system fully, especially in the corporate segment. This problem surfaced more than 4 years ago and has not yet been resolved.

**Comment by EXCV31** [comment] 2023-01-23 14:04
@kobaltd https://github.com/sddm/sddm/pull/776/ - we're waiting for 6 years.

**Comment by kobaltd** [comment] 2023-01-24 11:34
So this is the question. If you write about it "less", then for sure this problem will be solved "faster" :)

**Comment by Vogtinator** [comment] 2023-02-20 07:57
Duplicate of #716

**Closed as not planned by Vogtinator** 2023-02-20 07:57 UTC
