### ISSUE TITLE
SDDM fails to start the login Screen

### ISSUE THREAD

**Issue by nowshed-imran** [sddm/sddm#1339] opened 2020-12-03 16:54 UTC
After updating to version 0.19, `sddm` can't start the graphical interface. 
Journalctl log:
```
journalctl -xp 3 | grep sddm
sddm[362]: Failed to read display number from pipe
sddm[362]: Could not start Display server on vt 1
```
Trying to run SDDM from terminal:
sddm
```
[22:49:02.459] (II) DAEMON: Initializing...
[22:49:02.469] (II) DAEMON: Starting...
[22:49:02.469] (II) DAEMON: Logind interface found
[22:49:02.471] (II) DAEMON: Adding new display on vt 1 ...
[22:49:02.471] (II) DAEMON: Loading theme configuration from ""
[22:49:02.471] (II) DAEMON: Display server starting...
[22:49:02.471] (II) DAEMON: Adding cookie to "/var/run/sddm/{8d454d70-75e2-4efe-a5f4-c84134dcc740}"
/usr/bin/xauth:  error in locking authority file /var/run/sddm/{8d454d70-75e2-4efe-a5f4-c84134dcc740}
[22:49:02.480] (EE) DAEMON: Failed to write xauth file
[22:49:02.480] (EE) DAEMON: Could not start Display server on vt 1
^C[22:49:10.363] (WW) DAEMON: Signal received: SIGINT
```
Any bug that crashes the system should at least has some hotfix to it. I didn't find any. Switched to Lightdm for quite some times. I will provide any backtrace needed.

**Comment by nowshed-imran** [comment] 2020-12-03 17:05
@Pointedstick Sorry, to tag you. Any help?

**Comment by Pointedstick** [comment] 2020-12-04 14:16
Duplicate of https://github.com/sddm/sddm/issues/1316.

**Closed by Pointedstick** 2020-12-04 14:16 UTC
