### ISSUE TITLE
SDDM shows two windows in the same screen when running under Wayland

### ISSUE THREAD

**Issue by Kodehawa** [sddm/sddm#1605] opened 2022-10-27 02:57 UTC
Yes, this sounds weird, but it actually opens two windows (I can see them by getting to the Overview effect using the hot corner (which somehow is activated after logout, doesn't seem to activate on first startup, even though the bug persists)...

This might not be apparent to you unless the monitors are of different resolutions, which ends up on this weird behavior (and also causes the main monitor to show a cut off version of the greeter)

This happens on all themes, as the root cause seems to be the 2 windows it spawns. Switching to the window that spans the whole screen shows the greeter as usual.

Wayland config:
```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
CompositorCommand=kwin_wayland --no-lockscreen --inputmethod qtvirtualkeyboard
```

![PXL_20221026_235302323](https://user-images.githubusercontent.com/20606963/198180035-6d06e87b-b83d-415b-a826-7d229aac8f22.jpg)
![PXL_20221026_235253076](https://user-images.githubusercontent.com/20606963/198180042-8228102a-6fa0-4cfb-ab4b-249f0fddd45b.jpg)

**Comment by hadogenes** [comment] 2023-03-03 09:25
for me the commit 676fb59 solved the issue

**Comment by Vogtinator** [comment] 2023-03-03 09:26
Let's close this as a duplicate of #1672 (even though this is technically older)

**Closed as not planned by Vogtinator** 2023-03-03 09:26 UTC
Labels: duplicate
