### ISSUE TITLE
SDDM doesn't seem to handle starting Wayland sessions on seats without VTs well

### ISSUE THREAD

**Issue by n3rdopolis** [sddm/sddm#1769] opened 2023-07-23 02:24 UTC
Hi

This is SDDM v0.20.0

Trying SDDM on a kernel without VTs, and it seems that Wayland sessions don't start.
X11 sessions start, but what is interesting is that XDG_VTNR=-1
there are numerous logs in the journal saying that sddm is trying to jump to "VT -1"

I think it probably should be 0 I think when seats don't have VT's
I am not sure where to put it, but the correct way to check is probably logind's `CanTTY` query
https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html#CanTTY
that way, instead of hardcoding seat0, assuming it has VTs, it can be handled when seat0 does not have VTs.

It seems that I get similar behavior starting wayland sessions on non-seat0 seats too, not just tty-less seat0's
Trying to start kwin_wayland on a secondary seat (`-device pci-bridge-seat,chassis_nr=2,id=head.2` with QEMU)
and it goes back to the greeeter, but X11 kwin starts fine

Thanks

**Comment by n3rdopolis** [comment] 2023-08-01 03:02
```
diff --git a/src/daemon/Greeter.cpp b/src/daemon/Greeter.cpp
index c0437ae..3904780 100644
--- a/src/daemon/Greeter.cpp
+++ b/src/daemon/Greeter.cpp
@@ -197,8 +197,8 @@ namespace SDDM {
             env.insert(QStringLiteral("XDG_SEAT"), m_display->seat()->name());
             env.insert(QStringLiteral("XDG_SEAT_PATH"), daemonApp->displayManager()->seatPath(m_display->seat()->name()));
             env.insert(QStringLiteral("XDG_SESSION_PATH"), daemonApp->displayManager()->sessionPath(QStringLiteral("Session%1").arg(daemonApp->newSessionId())));
-            if (m_display->seat()->name() == QLatin1String("seat0"))
-                env.insert(QStringLiteral("XDG_VTNR"), QString::number(m_display->terminalId()));
+            //if (m_display->seat()->name() == QLatin1String("seat0"))
+            //    env.insert(QStringLiteral("XDG_VTNR"), QString::number(m_display->terminalId()));
             env.insert(QStringLiteral("XDG_SESSION_CLASS"), QStringLiteral("greeter"));
             env.insert(QStringLiteral("XDG_SESSION_TYPE"), m_display->sessionType());
             if (m_display->displayServerType() == Display::X11DisplayServerType) {
diff --git a/src/helper/backend/PamBackend.cpp b/src/helper/backend/PamBackend.cpp
index 8ffa24a..15778cc 100644
--- a/src/helper/backend/PamBackend.cpp
+++ b/src/helper/backend/PamBackend.cpp
@@ -253,7 +253,7 @@ namespace SDDM {
         const auto sessionType = sessionEnv.value(QStringLiteral("XDG_SESSION_TYPE"));
         const auto sessionClass = sessionEnv.value(QStringLiteral("XDG_SESSION_CLASS"));
         QString tty = VirtualTerminal::path(sessionEnv.value(QStringLiteral("XDG_VTNR")).toInt());
-        m_pam->setItem(PAM_TTY, qPrintable(tty));
+        //m_pam->setItem(PAM_TTY, qPrintable(tty));
         if (sessionType == QLatin1String("x11") && (sessionClass == QLatin1String("user") || !m_displayServer)) {
             QString display = sessionEnv.value(QStringLiteral("DISPLAY"));
             if (!display.isEmpty()) {
```
Gets Wayland greeters to start, AND gets user Wayland sessions to start on single-seat systems with CONFIG_VT=n
Maybe a call from `org.freedesktop.login1.Seat CanTTY` in the commented out locations is needed...



Doesn't work when X11 is the greeter,  I get a lot of 
```
kwin_core: Failed to open /dev/dri/card0 device (Device or resource busy)
kwin_wayland_drm: failed to open drm device at "/dev/dri/card0"
```

Seems that it is stopping the greeter, and trying to start it again, and then there is a race for /dev/dri/card0

When *wayland* is the greeter, issues don't happen until logoff, because it seems that instead of activating the logind session that the greeter is running under, it tries to start a new instance of Weston


x11-user gets similar behavior. I had to make a tweak to xwrap because it's not running under a console. 

Although it does appear to work better as I get the greeter UI when logging off, it does seem to leak Xorg instances, and I get new instance of Xorg every time I log out.

**Comment by n3rdopolis** [comment] 2023-08-01 12:07
OK, so the default config where Xorg runs as root, and doesn't allow kwin_wayland to run, I am guessing this is because logind can't kick it out (without VTs), so for VT-less systems, probably not worth pursuing supporting running Xorg as root, and distributions that want to disable VTs in their kernel will have to instead use `wayland` or `x11-user`

for `x11-user`, I had to set `ServerPath=/usr/lib/xorg/Xorg` this gets around all of that xwrap weirdness. At least on Kubuntu (and probably Debian too). And now oddly, it doesn't seem to be starting a bunch of ghost instances of Xorg anymore, so that is good.


With those two lines that enforce XDG_VTNR and PAM_VT disabled, sddm works on kernels with no VTs.
Not sure the best way to check CanTTY though to make those two changes less of a workaround...

**Comment by n3rdopolis** [comment] 2023-08-21 03:18
I know the places where the code needs to be changed, but I am not sure the best way to do it

**Comment by DimanNe** [comment] 2023-08-23 13:46
Same here...

Have you tried alternative Display Managers?

**Comment by n3rdopolis** [comment] 2023-08-23 17:56
gdm, (and lightdm IIRC)

**Comment by Pointedstick** [comment] 2023-08-25 18:22
Seems like a duplicate of https://github.com/sddm/sddm/issues/1762.

**Closed as completed by Pointedstick** 2023-08-25 18:22 UTC

**Comment by n3rdopolis** [comment] 2024-01-25 02:59
@Pointedstick I am not sure if this is a duplicate of #1762 to be 100% exact as this can happen on seat0 if the kernel has no VTs. The lines I commented out probably need to be guarded by a SeatCanTTY check

**Comment by Pointedstick** [comment] 2024-01-30 17:41
Cool, wanna submit a merge request?

**Comment by n3rdopolis** [comment] 2024-01-30 17:49
I tried to do it earlier, but it's been months and I forget what problems I had, but I think I struggled with a file that IIRC is auto-generated or something in `src/daemon/Greeter.cpp`  to create a `m_display->seat()->cantty()`   
and then IIRC, I think it was `src/helper/backend/PamBackend.cpp` there were no logind calls or something...

**Comment by n3rdopolis** [comment] 2024-01-30 20:24
So yeah, I might need a bit more help with an actual solution

src/helper/backend/PamBackend.cpp doesn't appear to call dbus afaik, so I don't know the way to work that check in that part, although, maybe 

src/daemon/Greeter.cpp 
can set XDG_VTNR to 0 or -1 if the seat can't tty, and then in
src/helper/backend/PamBackend.cpp if XDG_VTNR is 0 or less, unset the variable, and do not `m_pam->setItem(PAM_TTY, qPrintable(tty));`


Probably would still need a way to add a CanTTY() to src/daemon/SeatManager.cpp it seems?

**Comment by n3rdopolis** [comment] 2024-01-31 13:08
Although I  did try https://github.com/sddm/sddm/pull/1863
