### ISSUE TITLE
sddm needs to echo keyboard input and display on all monitors

### ISSUE THREAD

**Issue by skierpage** [sddm/sddm#1243] opened 2020-03-25 02:09 UTC
I run Fedora 31 KDE spin on a laptop with external monitor. When coming out of standby one or the other monitor takes time to display anything. Often I'll start typing and not see any response on the screen that's visible, then try to tab or mouse to the username field, but my inputs are going to the other screen, sometimes triggering unwanted behavior.
The fix is to display identically on all monitors, so it doesn't matter which screen is getting input. The Fedora boot screen that prompts for my disk encryption password does this, sddm should do the same.

**Comment by Pointedstick** [comment] 2020-11-29 01:17
Duplicate of https://github.com/sddm/sddm/issues/743

**Closed by Pointedstick** 2020-11-29 01:17 UTC
