### ISSUE TITLE
startx fails to work

### ISSUE THREAD

**Issue by xiangzhai** [sddm/sddm#492] opened 2015-09-14 01:40 UTC
sddm is running in tty1, swtich to tty2, startx, but failed:

XSEVTransSocketUNIXCreateListener SocketCreateListener failed. server already running

Linux Thinkpad-X250 4.2.0-3-ARCH #1 SMP PREEMPT Fri Sep 4 20:59:11 UTC 2015 x86_64 GNU/Linux
Qtv5.5.0
X11v1.6.3

**Comment by plfiorini** [comment] 2015-09-14 15:20
I don't think you can do that, it's either sddm or startx because sddm already start a Xorg server on DISPLAY=:0  -  To be precise maybe you can make startx use another DISPLAY

**Comment by plfiorini** [comment] 2015-09-14 15:20
Try Xorg :2 on tty2

**Comment by xiangzhai** [comment] 2015-09-15 02:15
Hi @plfiorini yup, it is able to ```startx -- :2``` but lightdm does ***NOT*** need to do so!

sddm [start X server](https://github.com/sddm/sddm/blob/master/src/daemon/XorgDisplayServer.cpp#L156) might be different with [lightdm](http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/head:/src/x-server-local.c#L417) ?

**Comment by plfiorini** [comment] 2015-09-15 09:11
@xiangzhai can you check on which display does lightdm runs the greeter?

**Comment by xiangzhai** [comment] 2015-09-15 09:31
Hi @plfiorini in my Arch box, lightdm start the greeter in tty7 

lightdm [get_vt](http://bazaar.launchpad.net/~lightdm-team/lightdm/trunk/view/head:/src/seat-xlocal.c#L139) then start X server and greeter on it.

Regards,
Leslie Zhai

**Comment by plfiorini** [comment] 2015-09-15 09:34
@xiangzhai ok but what X11 display? :)

What does the following command say?

```sh
ls -al /tmp/.X11-unix /tmp/.X*lock
```

**Comment by xiangzhai** [comment] 2015-09-17 12:26
```
-r--r--r-- 1 root root 11 Sep 17 20:21 /tmp/.X0-lock

/tmp/.X11-unix:
drwxrwxrwt 2 root root  60 Sep 17 20:21 .
drwxrwxrwt 9 root root 280 Sep 17 20:25 ..
srwxrwxrwx 1 root root   0 Sep 17 20:21 X0
```

**Comment by jleclanche** [comment] 2015-11-09 19:46
Closing as invalid, this is not a bug.

**Comment by plfiorini** [comment] 2015-11-09 19:47
@xiangzhai we never told anyone we would provide the exact same behavior as lightdm
since sddm doesn't prevent users from running another X display, i believe this is not a bug.

**Closed by jleclanche** 2015-11-09 19:46 UTC
Labels: invalid
