### ISSUE TITLE
sddm 0.12.0 does not focus the password field and the keyboard does nothing

### ISSUE THREAD

**Issue by Nek80** [sddm/sddm#501] opened 2015-09-21 19:41 UTC
When booted up SDDM comes up with the last used username selected and the password field apparently "focused" but in reality it is not, as when I try to type it does nothing. Also the keyboard keys (e.g. TAB) don't do anything at all at that moment until I use the mouse to click on the password field which then I can type in the password and also use TAB to move around the fields.

**Comment by SamuelGilbert42** [comment] 2015-10-06 16:00
I was about to report an issue for this and I saw that someone had already done it.

Every sddm functionality must be accessible with the keyboard.  I also agree that the password field must be focused by default.

**Comment by plfiorini** [comment] 2015-10-07 11:19
What theme are you using?

**Comment by heirecka** [comment] 2015-10-07 12:59
I encountered the same behaviour with the maui theme and just tested it with elarun, circles and maledives which show the same behaviour.
Version of Qt is 5.5.0.

For Maledives I just noticed that when you click outside of the box with the input fields, you also can't get back to the password field via tab key. I did not test that with other themes, though.

**Comment by mcurly** [comment] 2015-10-10 09:38
Hello.

I don't know if the issue being reported as a bug prevents it from having others (like myself) to report the same behavior as well.

Nevertheless I must enroll myself to the list of those who suffer from this issue (on both my pc's running up-to-date ArchLinux)

I also am going to refer this on the #archlinux irc channel, since I've been there yesterday and this was unknown there. Also, will subscribe to this thread to see if/how I can collaborate even further.

Regards.

**Comment by ctrlcctrlv** [comment] 2015-10-10 15:42
This isn't a themes bug @plfiorini. This affects all themes that I tried, and even when I added `focus: true` that didn't work. [Downstream (from you) KDE came up with this fix way back in July 2014](https://quickgit.kde.org/?p=plasma-workspace.git&a=blobdiff&h=275801dc5539a342276e4c9f6817ff3c80f7d020&hp=31423628c9a847344c0e3e27b98b73b6042cefe6&hb=dfc4b8b2a0e2b012f68f0192e29081ee230e8c03&f=lookandfeel%2Fcontents%2Floginmanager%2FMain.qml) and it still works today, I [copied it to the theme I'm using & opened a PR](https://github.com/Guidobelix/archlinux-themes-sddm/pull/1). However, I'm sure that everyone would appreciate you fixing this in SDDM proper.

Note that it does seem to work if you do e.g. `sddm-greeter --test --theme /usr/share/sddm/themes/archlinux-simplyblack` and open sddm-greeter from Xorg, but if you actually reboot and see SDDM it doesn't work.

**Comment by hhl** [comment] 2015-10-12 13:56
Mh, well i use a custom theme, based on elarun, without the lastUser  is displayed.
I set the username field to focus:true but nothing happen, i have to click with the mouse into textfield to type in the username, it would be great if focus:true works also on the username field, if it is empty.

**Comment by cyxou** [comment] 2015-10-24 12:09
I'm facing the same problem with all the standard sddm themes on Arch. But when I applied the archlinux-soft-gray theme from the [archlinux-themes-sddm](https://aur.archlinux.org/packages/archlinux-themes-sddm/) package, the problem is gone and the password field is focused ready for typing in.

**Comment by AlohaEh** [comment] 2015-11-02 17:06
It worked after I copied the timer cludge from the kde login manager into SddmComponents/PasswordBox.qml 
    TextBox { 
        id: txtMain 
        width: parent.width; 
        height: parent.height 
        font.pixelSize: 14 
        echoMode: TextInput.Password 
        focus: true 
        Timer { 
            interval: 200 
            running: true 
            onTriggered: txtMain.forceActiveFocus() 
        } 
    }

**Comment by hhl** [comment] 2015-11-09 10:29
One of the issue that "heirecka" reported above, 
>For Maledives I just noticed that when you click outside of the box with the input fields, you also can't get back to the password field via tab key.

can easily be fixed!
Just go to the background section of main.qml and insert there at the right place  
```qml
KeyNavigation.backtab: pw_entry; KeyNavigation.tab: user_entry
```
Here i have an example for the elarun main.qml
```qml
   Repeater {
           model: screenModel
           Background {
              x: geometry.x; y: geometry.y; width: geometry.width; height:geometry.height
               source: config.background
               fillMode: Image.PreserveAspectCrop
               
               /* insert here the TabKeyNavigation row */
               KeyNavigation.backtab: pw_entry; KeyNavigation.tab: user_entry
               
               onStatusChanged: {
                   if (status == Image.Error && source != config.defaultBackground) {
                    source = config.defaultBackground
                   }
               }
           }
       }
```

**Comment by doktor5000** [comment] 2015-11-09 20:48
Would that also fix the initial autofocus, or only allow to switch via tab key to first input field?

**Comment by hhl** [comment] 2015-11-10 08:08
No, that doesn't fix the initial focus, you need that "timer hack".
Also it works "only" if you included the timer hack.

**Comment by abbradar** [comment] 2015-11-19 14:47
I've hit this on 0.13.0 on NixOS, with `maui` theme.

**Comment by wedens** [comment] 2015-12-08 07:31
same problem with 0.13.0 on NixOS with default theme

**Comment by benjarobin** [comment] 2015-12-13 11:15
I did some preliminary test, I did put this inside the `.xinitrc`

    exec sddm-greeter --test --theme /usr/share/sddm/themes/maui

If I start Xorg with startx, the interface is started without focus on the password field.
Then I did change the `.xinitrc` to :
    
    twm &
    exec sddm-greeter --test --theme /usr/share/sddm/themes/maui

And now I did have the focus on the password field...

**Comment by benjarobin** [comment] 2015-12-13 11:41
I did run a bisect (between v0.11.0 and v0.12.0) and I found that the problematic commit is : 947b8d1

**Comment by benjarobin** [comment] 2016-02-29 14:24
I am so sorry to ask that but the project is dead ? There is a pull request that fix the issue...

**Comment by kainino0x** [comment] 2016-02-29 17:29
I have actually stopped experiencing this issue as of a few weeks ago (on two different systems, one of which has two displays). I am on Arch Linux with [extra/sddm 0.13.0-2](https://www.archlinux.org/packages/extra/x86_64/sddm/).

**Comment by mirh** [comment] 2016-02-29 18:20
I'm also on arch and it's still bugged in 0.13.0-2.

**Comment by dean36963** [comment] 2016-02-29 18:27
I am running a custom build of sddm in my Arch Linux that has [this](https://github.com/sddm/sddm/pull/573) pull request in. I have sddm-0.13.0-2 in my local packages, that was the last version I tried and that had the same issue for me too. Hopefully this can get merged and fixed soon.

**Closed** 2016-03-02 19:14 UTC
Labels: bug, themes

**Comment by markg85** [comment] 2016-03-21 22:27
Oh men...

I was just so fed up with this focus issue that i nose dived into the code to figure out what was wrong. I hacked several things before i checked out git to see if it had any updates. I'm glad it has, it fixes my no.1 issue :) Too bad i didn't look at git right from the start.

Please do release a new version with this. It's a _really_ annoying bug on multiscreen setups!
And thank you very much for fixing this!

**Comment by BrokenCanoe** [comment] 2016-07-14 20:12
This issue is still present in Manjaro 4.4.13-1-MANJARO
[KDE Plasma Version 5.6.5, Frameworks 5.23.0, Qt 5.6.1]

**Comment by klawdhfzasjhaa** [comment] 2017-05-28 20:47
With version 0.14.0-6.1 it's fixed. Yeeha! :)
I'm on OpenSUSE Tumbleweed.

**Comment by SharkWipf** [comment] 2018-01-20 00:28
I started experiencing this issue too, the moment I switched from the Intel modesetting driver to the DDX driver. Running version `0.17.0-r1` from the Gentoo unstable repos.

**Comment by jernejkubuntu** [comment] 2018-09-19 08:33
Kubuntu 18.04.1
sddm/bionic,now 0.17.0-1ubuntu7 amd64

when booting with external monitor, can't input password
the input field does not accept focus 
(text cursor is not present after clicking on input, or when trying with tab)

keyboard does work and can change to a different terminal

workaround:
1. change to a different terminal
2. find sddm ( ps -ef | grep sddm)
3. kill sddm it will auto restart ( sudo kill (proces number from 2) )

after the service restarts, it will automatically change your terminal to the graphic login.
the login will be working.

**Comment by LudSkywalker** [comment] 2021-08-18 17:55
In my case, an solution to fix the problem is search in de main.qml or login.qml in which part are located the form or the input for the password, and in this put the property focus:primaryScreen, this make than you can put your password, press enter and login, but you can't see the password field changing(this because in dual monitor the screen by default is not the primary), in the case of you are using lubuntu default theme, just replace "focus:true" to "focus:primaryScreen" at the line 130 in Main.qml located in /usr/share/sddm/themes/lubuntu/
