### ISSUE TITLE
Listed language on the login screen is wrong

### ISSUE THREAD

**Issue by mkoncek** [sddm/sddm#1767] opened 2023-07-21 08:58 UTC
On Fedora 38.
Version: sddm-0.20.0-1.fc38.x86_64

My login screen at startup lists the language `English (US)`.
I set my default language as `Slovak` and it is indeed what is used when typing the password.
Therefore the **used** language is correct (Slovak) but the language listed is wrong (English)

**Comment by Vogtinator** [comment] 2023-07-21 09:01
You mean the keyboard layout? If so, this is https://github.com/sddm/sddm/issues/1528.

**Comment by travier** [comment] 2023-07-21 10:21
I think it's a different issue as it's on top of the Wayland support.

The language selection "works" (it changes the languages used as intput) but sometimes (not clear exactly when) the language displayed in the selector is not the one used in the input field.

I think (but needs confirmation) that it happens on (re)boot, where the default English language is selected / displayed even though the "correct" language is used for the input.

**Comment by mkoncek** [comment] 2023-07-21 10:24
I also remember the previously mentioned issue was in Fedora some time ago, then it got more or less fixed.
However the current situation is like I described.
Adding my output:
```
$ localectl
System Locale: LANG=en_US.UTF-8
    VC Keymap: sk-qwerty
   X11 Layout: sk
```

**Comment by Vogtinator** [comment] 2023-07-21 10:37
The locale1 integration was broken by design and removed again for 0.20.

**Comment by enkeyz** [comment] 2023-09-28 19:25
This issue still persist on Fedora 38 KDE spin.

Related forum post: https://forums.fedoraforum.org/showthread.php?331233-SDDM-doesn-t-respect-keyboard-layout-set-in-localectl

**Comment by bitrate16** [comment] 2023-09-29 16:41
Can't log in due to this issue: can not change keyboard layout
Could get fixed default locale with:
```
localectl set-locale LANG=en_US.utf8
localectl set-keymap us
localectl set-x11-keymap us
```

**Comment by tazihad** [comment] 2023-10-12 09:40
I face same issue. keyboard is wrong in sddm

**Comment by Pointedstick** [comment] 2023-10-26 22:09
Fixed with https://github.com/sddm/sddm/pull/1797. Well... hidden, at least. Effectively fixed from the user's POV.

**Closed as completed by Pointedstick** 2023-10-26 22:09 UTC
Labels: needinfo, wayland

**Comment by ghost** [comment] 2023-10-27 02:47
Hi, i have the same problem, but in pt_br.

**Comment by ghost** [comment] 2023-10-27 02:48
localectl set-locale LANG=pt_BR.utf8
localectl set-keymap br
localectl set-x11-keymap br
?

**Comment by ghost** [comment] 2023-10-27 02:52
Done.
