### ISSUE TITLE
logout problems with pam_gnome_keyring.so

### ISSUE THREAD

**Issue by inflextau** [sddm/sddm#333] opened 2014-12-22 22:08 UTC
I'm using arch. When adding pam_gnome_keyring.so to   /etc/pam.d/sddm with the aim of unlocking Gnome Keyring on log in, if I subsequintly log out X crashes. I am then forced to drop to a different tty and issue a systemctl restart sddm. This seems simlair to that reported here https://github.com/sddm/sddm/issues/286

**Comment by plfiorini** [comment] 2015-10-27 15:42
Duplicate of #286

**Closed by plfiorini** 2015-10-27 15:42 UTC
Labels: invalid
