### ISSUE TITLE
Overlap on multiple screen with different resolutions

### ISSUE THREAD

**Issue by guoyunhe** [sddm/sddm#805] opened 2017-03-27 17:27 UTC
![img_20170327_200045](https://cloud.githubusercontent.com/assets/5836790/24369193/de951aea-132b-11e7-965e-9639957aaaac.jpg)

openSUSE Tumbleweed, SDDM 0.14.0, Qt 5.7.1

Primary screen of laptop has resolution of 1920x1080. External screen is 1280x1024. When system start, the SDDM display on external screen will have a clone overlap on primary screen. As shown in photo.

**Comment by muesli** [comment] 2017-07-05 16:29
Same here with 0.14.0 and Qt 5.9.1 on ArchLinux.

**Comment by 4risu** [comment] 2017-10-09 10:02
I have the same issue.

**Comment by guoyunhe** [comment] 2018-05-01 14:28
Any response from developers?

**Comment by muesli** [comment] 2018-05-01 18:07
Afraid not, the issue is still existent and annoying me on a daily basis on multiple machines.

**Comment by modislaszlo** [comment] 2018-07-31 14:53
I have a similar issue. My external monitor has bigger resolution(quad HD) as my laptop monitor(full HD) so only a part of the login screen is displayed on laptop monitor.

**Comment by MayeulC** [comment] 2018-10-09 09:54
Duplicate of #719?

**Comment by guoyunhe** [comment] 2018-10-09 09:56
> Duplicate of #719?

Yes, I think it is the same issue. However, neither got response from developers.

**Comment by MayeulC** [comment] 2018-10-09 11:10
Yeah, it looks like the project doesn't get the man-hours it needs, which is a shame. However, there is mention of a workaround in the other thread (disabling xf86-video-intel in favor of xf86-video-modesetting), which might be worth a try, especially as the ddx driver seems to be [advised against](https://wiki.archlinux.org/index.php/Intel_graphics#Installation) nowadays.

**Comment by muesli** [comment] 2018-10-26 23:38
I can confirm that ditching xf86-video-intel in favor of KMS seems to resolve the SDDM issue.

**Comment by treier57lol** [comment] 2019-06-17 07:55
Also having the same issue.

**Comment by impresionista** [comment] 2020-04-02 20:24
I'm having the same issue, anyone found a solution? I'm usign ArchLabs (Arch based distro with the same repos as Arch).

**Comment by treier57lol** [comment] 2020-04-03 06:45
That is interesting, because after I switched over to Manjaro in March, the issue has gone away. Of course, I'm an idiot for not providing the SDDM version when I was on Kubuntu 19.04. On Manjaro 19.0.2 I'm running SDDM 0.18.1-2 and the issue is long gone for me. I did have to manually set my DPI for the scaling to be correct, but otherwise there is no overlapping. What version are you on?

**Comment by MayeulC** [comment] 2020-04-07 15:03
@impresionista, have you tried the workaround above? (get rid of xf86-video-intel)

**Comment by impresionista** [comment] 2020-04-08 13:35
@treier57lol I'm using sddm 0.18.1-2 and sddm-kcm 5.18.4.1-1

@MayeulC Not yet. I was not sure what driver to use instead and I really need my pc to work in this pandemic days because i'm working and coursing online. I couldn't find some time to do some research about this solution.

**Comment by impresionista** [comment] 2020-04-18 19:28
@MayeulC I managed to uninstall the xf86-video-intel package and everything is working properly.Thanks for the help and sorry for the inconvenience!

**Comment by Pointedstick** [comment] 2020-11-28 23:59
Yeah, duplicate of https://github.com/sddm/sddm/issues/719

**Closed by Pointedstick** 2020-11-28 23:59 UTC
Labels: multi-monitor
