### ISSUE TITLE
Login screen font way too small (on high-dpi screen)

### ISSUE THREAD

**Issue by RalfJung** [sddm/sddm#1169] opened 2019-05-19 11:40 UTC
I just installed SDDM (together with KDE) on my laptop with a 4k 15" screen. I'd expect SDDM to detect this as a high-DPI situation, and show the login prompt in a readable size. Unfortunately, it does not -- the font is so small I can barely read anything.

**Comment by zeronote** [comment] 2019-06-28 00:28
Although #1056 is still valid for me (4k on 13.3''), have you [enabled HiDPI](https://wiki.archlinux.org/index.php/SDDM#Enable_HiDPI) ?

**Comment by RalfJung** [comment] 2019-06-28 06:27
But won't that mean that when my external screen is connected, it makes everything ridiculously zoomed in?

Currently what happens in that situation is that I get two login screens that partally overlap each other -- so on the external screen it looks normal, but on the laptop screen I can see one login prompt in the top-left quadrant, and then behind that another login spanning the entire screen. Looks like SDDM has one login prompt per screen, ever if those screens (partially) overlap

**Comment by zeronote** [comment] 2019-07-04 10:43
> But won't that mean that when my external screen is connected, it makes everything ridiculously zoomed in?

Probably yes, but it depends mostly on your external screen characteristic.

> Currently what happens in that situation is that I get two login screens that partally overlap each other -- so on the external screen it looks normal, but on the laptop screen I can see one login prompt in the top-left quadrant, and then behind that another login spanning the entire screen. Looks like SDDM has one login prompt per screen, ever if those screens (partially) overlap

As above, if your external monitor DPI value is way different from your laptop 4K screen one, setting the HiDPI value in sddm.conf won't be the best solution.

If changing the HiDPI value in sddm.conf fix your issue, I suggest to close this bug report and open a new one about the external monitor topic.

**Comment by RalfJung** [comment] 2019-07-17 21:15
> As above, if your external monitor DPI value is way different from your laptop 4K screen one

It is. The external screen is a 24" screen with resolution 1920x1200.

I have added to my `sddm.conf`:
```
[X11]
EnableHiDPI=true

[Wayland]
EnableHiDPI=true
```
This does not help: the text is still unreadably small.

> If changing the HiDPI value in sddm.conf fix your issue, I suggest to close this bug report and open a new one about the external monitor topic.

As far as I am concerned the bug is about SDDM not doing the right thing out-of-the box. If I need a a magnifying glass for the first log-in, the fact that I can fix this by logging in and then changing the configuration does not help. In contrast, for example, the hard disk encryption password prompt sown by plymouth is readable without requiring any manual configuration.

**Comment by zeronote** [comment] 2019-07-23 06:13
> As far as I am concerned the bug is about SDDM not doing the right thing out-of-the box. 

Totally agree about that, SDDM is actually far away to work properly out-of-the box on a HiDPI display.
And when it comes to different HiDPI displays with different DPI each, it is just a nightmare.

To fix the small font issue on my DELL xps 13 4k display, I use the following in my sddm.conf:
```
[X11]
EnableHiDPI=true
ServerArguments=-nolisten tcp -dpi 168
```
but that value (168) is not correct when I use my external QHD display where the Font size is now too big.

**Comment by rypz79** [comment] 2019-08-11 05:37
I have the same problem on my Kubuntu 19.04 KDE 5.16.4 with my FHD 1920x1080 13" laptop display.
I've set my laptop screen resolution on 1368x768 with 1.1 scaling this resulted in a 97x97 resolution on the X11 unfortunately it doesn't apply to the SDDM login screen.
I've tried to change `sddm.conf`  which is located in `/etc/init`:
```
# SDDM
#
# The display manager service manages the X servers running on the
# system, providing login and auto-login services
#
# based on lightdm upstart script

description     "SDDM"
author          "Rohan Garg <rohangarg@kubuntu.org>"

[X11]
EnableHiDPI=true
ServerArguments=-nolisten tcp -dpi 97

start on ((filesystem
           and runlevel [!06]
           and started dbus
           )
          or runlevel PREVLEVEL=S)

stop on runlevel [016]

respawn
respawn limit 2 15

emits login-session-start
emits desktop-session-start
emits desktop-shutdown

script
    if [ -n "$UPSTART_EVENTS" ]
    then
        # Check kernel command-line for inhibitors, unless we are being called
        # manually
        for ARG in $(cat /proc/cmdline); do
            if [ "$ARG" = "text" ]; then
		plymouth quit || : 
                stop
		exit 0
            fi
        done

        [ ! -f /etc/X11/default-display-manager -o "$(basename $(cat /etc/X11/default-display-manager 2>/dev/null))" = "sddm" ] || { stop; exit 0; }
        plymouth quit
        clear >/dev/tty7
    fi
    exec sddm
end script

post-start script
    sleep 5
    clear > /dev/tty7
end script

post-stop script
        clear > /dev/tty7
        sleep 1
        if [ "$UPSTART_STOP_EVENTS" = runlevel ]; then
                initctl emit desktop-shutdown
        fi
end script
```
But it's still shows small size login screen.
Any suggestions ?

TNX

**Comment by Pointedstick** [comment] 2020-11-29 01:31
Duplicate of https://github.com/sddm/sddm/issues/692

**Closed by Pointedstick** 2020-11-29 01:31 UTC
