### ISSUE TITLE
PAM authentication error causes SDDM crash

### ISSUE THREAD

**Issue by Samuil1337** [sddm/sddm#1882] opened 2024-03-05 13:14 UTC
Hello guys!

Thank you so much for your hard work and the new release. Unfortunately, after I updated to 0.21.0.14 (what pacman reports on the sddm-git package), my screen freezes or rather SDDM crashes: No login screen or TTY, but some boot messages persist. Changing VTs luckily works. This is the journal log about it:
```
Mär 05 13:37:30 XENON sddm[1441]: Initializing...
Mär 05 13:37:30 XENON sddm[1441]: Starting...
Mär 05 13:37:30 XENON sddm[1441]: Logind interface found
Mär 05 13:37:30 XENON sddm[1441]: Adding new display...
Mär 05 13:37:30 XENON sddm[1441]: Loaded empty theme configuration
Mär 05 13:37:30 XENON sddm[1441]: Using VT 1
Mär 05 13:37:30 XENON sddm[1441]: Display server started.
Mär 05 13:37:30 XENON sddm[1441]: Socket server starting...
Mär 05 13:37:30 XENON sddm[1441]: Socket server started.
Mär 05 13:37:30 XENON sddm[1441]: Loading theme configuration from "/usr/share/sddm/themes/sugar-candy/theme.conf"
Mär 05 13:37:30 XENON sddm[1441]: Greeter starting...
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] Starting...
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] Authenticating...
Mär 05 13:37:30 XENON sddm-helper[1445]: pam_warn(sddm-greeter:auth): function=[pam_sm_authenticate] flags=0 service=[sddm-greeter] terminal=[<unknown>] user=[sddm] ruser=[<unknown>] rhost=[<unknown>]
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] authenticate: Authentication failure
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] returning.
Mär 05 13:37:30 XENON sddm[1441]: Error from greeter session: "Authentication failure"
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] Asked to close the session but it wasn't previously open
Mär 05 13:37:30 XENON sddm-helper[1445]: [PAM] Ended.
Mär 05 13:37:30 XENON sddm[1441]: Auth: sddm-helper exited with 1
Mär 05 13:37:30 XENON sddm[1441]: Greeter stopped. SDDM::Auth::HELPER_AUTH_ERROR
```
It seems like the SDDM account used in rootless-x11/Wayland is for some reason unable to authenticate, however I didn't change anything on my system (except updating SDDM that is). Could this be related to the removal of the PAM modules? 

Thanks in advance,
Samuil1337

**Comment by sukanka** [comment] 2024-03-05 16:56
Oh, I just got the same error on archlinux with `sddm-git-0.21.0.14.gae072f90-2` 
(commit id [ae072f901671b68861da9577e3e12e350a9053d5](https://github.com/sddm/sddm/commit/ae072f901671b68861da9577e3e12e350a9053d5) )
and when I finally downgraded to `sddm-git-0.21.0.11.gcc03fabf-1`
 (commit id [cc03fabf2f3025842cee30b5f05d20f56b6a2270](https://github.com/sddm/sddm/commit/cc03fabf2f3025842cee30b5f05d20f56b6a2270) )
it then works fine.

edit: add my previous error log
https://fars.ee/JfOk

**Comment by Samuil1337** [comment] 2024-03-05 18:35
Thank you very much. Do you know how I can downgrade exactly? I don't have the old package anymore.

**Comment by Samuil1337** [comment] 2024-03-05 19:33
I found out how to do this. You have to change the source line in the PKGBUILD to:
`source=("git+https://github.com/sddm/sddm.git#commit=cc03fabf2f3025842cee30b5f05d20f56b6a2270")`

I don't know if I should close, but most likely this should be patched by the SDDM package maintainer and not the team itself.

**Comment by edt-xx** [comment] 2024-03-05 20:33
I am also on Arch and am getting the same log as reported by Samuil1337.   Does sddm-helper need additional permissions?  (eg something along the lines of: chmod u+s /usr/lib/sddm/sddm-helper or an act ? )

**Comment by Vogtinator** [comment] 2024-03-05 20:36
Duplicate of https://github.com/sddm/sddm/issues/1881.

The Arch packaging needs to be adjusted.

**Closed as not planned by Vogtinator** 2024-03-05 20:36 UTC
