### ISSUE TITLE
SDDM is waiting 30 seconds for fingerprint even though I use the password to log in

### ISSUE THREAD

**Issue by eylenburg** [sddm/sddm#1840] opened 2023-12-13 16:47 UTC
On my system, when entering the password to log in and pressing "enter", SDDM seems to be frozen for 30 seconds doing absolutely nothing, before the Plasma desktop starts loading. `journalctl -b -u display-manager.service -o short-monotonic` shows that this is due to SDDM waiting for the fingerprint:

```
[   21.480231] localhost.localdomain sddm[1481]: Authentication information: SDDM::Auth::INFO_UNKNOWN "Place your right index finger on the fingerprint reader"
[   51.484220] localhost.localdomain sddm[1481]: Authentication information: SDDM::Auth::INFO_UNKNOWN "Verification timed out"
```

I confirmed this by setting up a new user without fingerprints and log in is immediate.

When I unlock the device using my fingerprint after standby, this happens immediately without SDDM "freezing".

Why is SDDM waiting for the fingerprint during the initial log in when I use my password anyway? 

I'm not completely sure if this is a SDDM bug or something else. I set up the fingerprint in the KDE System Settings (where it even says it's just for unlocking the screen but "logging into your system with your fingerprint is not supported yet") and then because it didn't work for unlocking the screen is ran `sudo pam-config --add --fprintd`

Running OpenSUSE Tumbleweed with SDDM version "0.20.0-3.2".

**Comment by Vogtinator** [comment] 2023-12-13 16:49
The lockscreen is entirely independent for SDDM. SDDM itself does not really support login with fingerprints, the 30s delay is a symptom of that.

**Comment by Vogtinator** [comment] 2023-12-13 16:50
See also https://github.com/sddm/sddm/pull/1220

**Comment by Vogtinator** [comment] 2023-12-13 16:50
Closing as duplicate of https://github.com/sddm/sddm/issues/284

**Closed as not planned by Vogtinator** 2023-12-13 16:50 UTC
Labels: duplicate, feature

**Comment by eylenburg** [comment] 2023-12-13 17:51
> The lockscreen is entirely independent for SDDM. SDDM itself does not really support login with fingerprints, the 30s delay is a symptom of that.

Thank you. Is there any way currently to tell SDDM to completely ignore the fingerprint for the log in (but not the lockscreen) just to avoid that 30s delay? Or does it need the pull request from https://github.com/sddm/sddm/pull/1220 to avoid the delay?

**Comment by Vogtinator** [comment] 2023-12-13 19:56
You could remove fprintd from the pam-config managed file again and add it manually to the `kde` service by copying it from `/usr/lib/pam.d/kde` to `/etc/pam.d/kde` and adding the fprint entry. With Plasma 6, the lockscreen will always do fingerprint unlocking if available, regardless of pam-config.

**Comment by eylenburg** [comment] 2023-12-13 21:39
Very good, I can't wait for Plasma 6!
