### ISSUE TITLE
Password fields are not in-sync across multiple screens

### ISSUE THREAD

**Issue by tysontan** [sddm/sddm#1088] opened 2018-10-18 01:27 UTC
In a multi-screen setup, password input fields across screens are not in-sync. Each screen records the password separately. This can bring about confusion especially for new users.

I suggest we either:
A) Display only one login module on one of the screens
B) We sync all password fields

**Comment by Pointedstick** [comment] 2020-11-29 01:33
Duplicate of https://github.com/sddm/sddm/issues/743

**Closed by Pointedstick** 2020-11-29 01:33 UTC
