### ISSUE TITLE
Upgrade 0.11 -> 0.12 (Arch) Login screen layout makes it impossible to login.

### ISSUE THREAD

**Issue by CommanderAlchemy** [sddm/sddm#507] opened 2015-10-04 14:56 UTC
During upgrade from sddm 0.11 -> 0.12 (Arch) it cannot longer display the login screen correctly. I have 3 monitors with configuration, (portrait, 1080x1920 + landscape 1920x1080 + landscape 1920x1080).

Before 0.12 it would show login screen on primary monitor (middle) and then just show some background on the other monitors. However now with the update it tries to center the position of the login screen between my left 2 monitors. It also cuts off everything few cm to the right after the profile image making it impossible to enter username/password, only thing i can really see is the profile img and the session dropdown.

**Comment by CommanderAlchemy** [comment] 2015-10-04 15:02
Hm probably related to #496

**Comment by plfiorini** [comment] 2015-10-27 15:53
Duplicate of #496 which is closed now.

**Closed by plfiorini** 2015-10-27 15:53 UTC
Labels: multi-monitor
