### ISSUE TITLE
SDDM Mixes seats in multi-seat setup (Failed to create session: TTY tty1 is virtual console but seat seat1 is not seat0)

### ISSUE THREAD

**Issue by DimanNe** [sddm/sddm#1786] opened 2023-08-23 13:41 UTC
It looks like login session from a second seat does get initialised properly. I have two seats logged in, and this is what I observe:

**Only one session is reported by loginctl**:

```
loginctl list-sessions
SESSION  UID USER    SEAT  TTY
      4 1000 dimanne seat0 tty2

1 sessions listed.
```

**Directory `/run/user/1001` is not created**.

**`DBUS_SESSION_BUS_ADDRESS` of the second user is empty**.

**systemctl --user list-units prints**:
```
Failed to connect to bus: No medium found
```

**Finally, `loginctl session-status` says**:

```
Could not get properties: Unknown object 'org/freedesktop/login1/session/auto'
```

### Why it happens

I think this happens because sddm failed to properly initialise login session.

This is how sddm logs look for "good" login:

```
Aug 20 09:52:17 impedance sddm[8212]: Authentication for user  "dimanne"  successful
Aug 20 09:52:17 impedance sddm-greeter[8590]: Message received from daemon: LoginSucceeded
Aug 20 09:52:17 impedance sddm-helper[9033]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Aug 20 09:52:17 impedance sddm-helper[9033]: pam_limits(sddm:session): Could not set limit for 'nofile' to soft=16777216, hard=16777216: Operation not permitted; uid=0,euid=0
Aug 20 09:52:17 impedance sddm-helper[9033]: pam_unix(sddm:session): session opened for user dimanne(uid=1000) by (uid=0)
Aug 20 09:52:17 impedance sddm-helper[8362]: [PAM] Closing session
Aug 20 09:52:17 impedance sddm-helper[8362]: pam_unix(sddm-greeter:session): session closed for user sddm
Aug 20 09:52:17 impedance sddm-helper[8362]: [PAM] Ended.
Aug 20 09:52:17 impedance sddm[8212]: Auth: sddm-helper exited successfully
Aug 20 09:52:17 impedance sddm[8212]: Greeter stopped. SDDM::Auth::HELPER_SUCCESS
Aug 20 09:52:17 impedance sddm-helper[9033]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
Aug 20 09:52:17 impedance sddm-helper[9078]: pam_kwallet5: final socket path: /run/user/1000/kwallet5.socket
Aug 20 09:52:17 impedance sddm-helper[9033]: pam_env(sddm:session): deprecated reading of user environment enabled
Aug 20 09:52:17 impedance sddm-helper[9033]: Writing cookie to "/tmp/xauth_vDhCDz"
Aug 20 09:52:17 impedance sddm-helper[9033]: Starting X11 session: "" "/etc/sddm/Xsession \"/usr/bin/startplasma-x11\""
Aug 20 09:52:17 impedance sddm[8212]: Session started true
Aug 20 12:27:05 impedance sddm-greeter[8534]: Reading from "/usr/share/xsessions/plasma.desktop"
```

And this is how they look for 2nd seat

```
Aug 20 12:27:05 impedance sddm[8212]: Authentication for user  "yulia"  successful
Aug 20 12:27:05 impedance sddm-greeter[8534]: Message received from daemon: LoginSucceeded
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_kwallet5(sddm:setcred): pam_kwallet5: pam_sm_setcred
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_limits(sddm:session): Could not set limit for 'nofile' to soft=16777216, hard=16777216: Operation not permitted; uid=0,euid=0
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_unix(sddm:session): session opened for user yulia(uid=1001) by (uid=0)
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_systemd(sddm:session): Failed to create session: TTY tty1 is virtual console but seat seat1 is not seat0
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_kwallet5(sddm:session): pam_kwallet5: pam_sm_open_session
Aug 20 12:27:05 impedance sddm-helper[56832]: pam_kwallet5: final socket path: /tmp/kwallet5_yulia.socket
Aug 20 12:27:05 impedance sddm-helper[56829]: pam_env(sddm:session): deprecated reading of user environment enabled
Aug 20 12:27:05 impedance sddm-helper[56829]: Writing cookie to "/tmp/xauth_MzDsqA"
Aug 20 12:27:05 impedance sddm-helper[56829]: Starting X11 session: "" "/etc/sddm/Xsession \"/usr/bin/startplasma-x11\""
Aug 20 12:27:05 impedance sddm[8212]: Session started true
Aug 20 12:27:05 impedance sddm-helper[8399]: [PAM] Closing session
Aug 20 12:27:05 impedance sddm-helper[8399]: pam_unix(sddm-greeter:session): session closed for user sddm
Aug 20 12:27:05 impedance sddm-helper[8399]: [PAM] Ended.
Aug 20 12:27:05 impedance sddm[8212]: Auth: sddm-helper exited successfully
Aug 20 12:27:05 impedance sddm[8212]: Greeter stopped. SDDM::Auth::HELPER_SUCCESS
```

Note:

`Failed to create session: TTY tty1 is virtual console but seat seat1 is not seat0`

**Comment by Pointedstick** [comment] 2023-08-25 18:23
Seems like a duplicate of https://github.com/sddm/sddm/issues/1762.

**Closed as completed by Pointedstick** 2023-08-25 18:23 UTC
