### ISSUE TITLE
Custom user icon are not selected.

### ISSUE THREAD

**Issue by martinrotter** [sddm/sddm#300] opened 2014-10-28 07:03 UTC
I have accountsservice installed. Each user contains ".face" icon file in its home directory. All users have set their icons via accountsservice.

SDDM does not seem to take advantage of accountsservice functionality to display user icons. For me, option "FacesDir=/usr/share/sddm/faces" is not enough, because it requires manual steps for copying icons to given folder, which is not quite user-friendly.

**Comment by plfiorini** [comment] 2015-07-03 09:22
Duplicate of #174

**Closed by plfiorini** 2015-07-03 09:22 UTC
