### ISSUE TITLE
Account with expired password

### ISSUE THREAD

**Issue by marcelrc** [sddm/sddm#716] opened 2016-10-06 12:00 UTC
My computer has KDE Neon installed, and is joined in an ActiveDirectory domain.
At domain server, I create a "test" user with "expired password" status. On windows clients, after "test" user logins, is showed to user a screen to him input the new password twice.

In SDDM (default theme breeze), after this user logins, the SDDM restarts and goes back to the login screen. My syslog shows:

...
Oct 4 13:24:46 ...hostname... sddm-greeter[3275]: Reading from "/usr/share/xsessions/plasma.desktop"
Oct 4 13:24:46 ...hostname... sddm[1023]: Message received from greeter: Login
Oct 4 13:24:46 ...hostname... sddm[1023]: Reading from "/usr/share/xsessions/plasma.desktop"
Oct 4 13:24:46 ...hostname... sddm[1023]: Session "/usr/share/xsessions/plasma.desktop" selected, command: "/usr/bin/startkde"
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Starting...
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Authenticating...
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Preparing to converse...
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Conversation with 1 messages
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Preparing to converse...
Oct 4 13:24:46 ...hostname... sddm-helper[3307]: [PAM] Conversation with 3 messages
**Oct 4 13:24:46 ...hostname... sddm[1023]: Authentication information: "Password expired. You must change it now."
Oct 4 13:24:46 ...hostname... kernel: [ 785.032356] traps: sddm-helper[3307] trap stack segment ip:42c743 sp:7ffd256b9b40 error:0 in sddm-helper[400000+37000]
Oct 4 13:24:47 ...hostname... sddm[1023]: Authentication error: "Process crashed"
Oct 4 13:24:47 ...hostname... sddm[1023]: Auth: sddm-helper crashed (exit code 7)
Oct 4 13:24:47 ...hostname... sddm[1023]: Authentication error: "Process crashed"
Oct 4 13:24:47 ...hostname... sddm[1023]: Auth: sddm-helper exited with 7**
Oct 4 13:24:47 ...hostname... sddm[1023]: Greeter stopping...
Oct 4 13:24:47 ...hostname... sddm[1023]: Socket server stopping...
Oct 4 13:24:47 ...hostname... sddm[1023]: Socket server stopped.
Oct 4 13:24:47 ...hostname... sddm[1023]: Display server stopping...
Oct 4 13:24:47 ...hostname... sddm-greeter[3275]: The X11 connection broke (error 1). Did the X11 server die?
Oct 4 13:24:47 ...hostname... sddm-helper[3265]: [PAM] Ended.
...

**Comment by hoehnth** [comment] 2017-02-28 14:25
Handling expired password is not yet supported (v0.14.0) but planned for Milestone 1.0 ( see issue #472 ).
In the meantime I have implemented it with a new branch but dont know if and when it gets merged. (pull request https://github.com/sddm/sddm/pull/776)

**Comment by ZaMaZaN4iK** [comment] 2020-05-03 12:14
Any updates?

**Comment by RafaelLinux** [comment] 2020-05-04 02:43
I think not

**Comment by hoehnth** [comment] 2020-05-04 08:13
Maybe maintainers are still busy with liri os which sddm is just a small part of, so they dont have the time to care for this issue...

**Comment by RafaelLinux** [comment] 2020-05-07 00:15
Yep, but unfortunately this way we will never be able to integrate Linux in an Active Directory environment  :(

**Comment by semidark** [comment] 2020-05-11 14:47
I am testing the AD password expiring feature on different DisplayManager implementations available in Ubuntu. 

Since sddm dosn't support this at all, I will use lightdm as default DisplayManager. It implements this quite nice.

**Comment by bobOnGitHub** [comment] 2022-09-28 14:30
An alternative to replacing sddm is to get the user to ctrl+alt+F\<n\> to get a terminal login prompt and do the password change there, then logout (exit) in that terminal and ctrl-alt-F\<n\> back to the sddm for a login to KDE. ( I've been reading that people are having other issues with LightDM ) Should work everywhere but tested on Alma Linux 8.6.

**Comment by RafaelLinux** [comment] 2022-09-28 17:55
It seems this issue is not "popular" so will be unsolved for long time ...

**Comment by bobOnGitHub** [comment] 2022-09-28 20:20
@RafaelLinux, 7 yrs or more and counting.... things have come a long way in that time but this doesn't look good to any organisation who might be considering KDE. Though, personally I can live with it considering the alternatives.

**Comment by RafaelLinux** [comment] 2022-09-29 00:23
Unfortunately, to get business with Windows local domains (AD)  to adopt Linux + Plasma, is impossible if developers ignores this kind of issues  :(

**Comment by Vogtinator** [comment] 2023-02-20 07:58
Duplicate of #472

**Closed by Vogtinator** 2023-02-20 07:58 UTC
