### ISSUE TITLE
Focus is not on password field with an external monitor

### ISSUE THREAD

**Issue by kustodian** [sddm/sddm#1171] opened 2019-05-22 10:42 UTC
I'm using `sddm 0.18.1` on Arch and if I use a Laptop monitor password field is focused correctly, but if I use an external monitor the password is not focused. Even if I only use the external monitor and close the laptop lid which powers off the laptop monitor, the password field is still not focused.

This issue is not a duplicate to #612, because the password field is correctly focused on the laptop monitor, the bug is only on the external one.

**Comment by simgunz** [comment] 2019-12-07 11:10
I can confirm this behavior on Manjaro.

**Comment by Rorschach1010** [comment] 2020-02-10 21:55
Same here on Manjaro using the Breath Theme

**Comment by kustodian** [comment] 2020-02-11 11:20
One important fact is that even though on the monitor the password field is not focused, if you start typing the password you cannot see that you are typing it, but when you press Enter it actually inputs the password and starts login. Which is cool, but it's still a bug.

**Comment by Rorschach1010** [comment] 2020-02-11 17:38
> One important fact is that even though on the monitor the password field is not focused, if you start typing the password you cannot see that you are typing it, but when you press Enter it actually inputs the password and starts login. Which is cool, but it's still a bug.

lol, thats really working. Funny actually but as you said, its still a bug and should be fixed. Thanks for pointing that out, though :)

**Comment by cuzrawr** [comment] 2020-07-12 17:56
Same on arch-linux.

**Comment by Pointedstick** [comment] 2020-11-28 23:50
Duplicate of https://github.com/sddm/sddm/issues/514

**Closed by Pointedstick** 2020-11-28 23:50 UTC

**Comment by marvin-jens** [comment] 2021-07-01 10:48
I have a variant of this issue with sddm 0.18.1 on neon 18.04. When waking the screens up from power saving it appears that the focus switches between the two monitors. I typically type my password right away, while the screens are still dark but then end up with half of the password on one screen and half on the other. I then have to wait for the timeout before I can enter the password and unlock properly. It gets quite irritating after the hundredth time or so... ^^
Same setup as described above: laptop with external screen via HDMI. Cursor is usually on the external when screens go to power save mode. Laptop by itself works as expected.
