### ISSUE TITLE
Autologin in X11 does not work if session name is absolute path

### ISSUE THREAD

**Issue by arvidjaar** [sddm/sddm#1607] opened 2022-10-29 20:14 UTC
sddm tries to detect session type by searching for session name in corresponding directories:

https://github.com/sddm/sddm/blob/fc24321541f6f65b7d1aac89cd82336ffd53e1a0/src/daemon/Display.cpp#L198

`findSessionEntry` simply calls `dir.exists` for session name:

https://github.com/sddm/sddm/blob/fc24321541f6f65b7d1aac89cd82336ffd53e1a0/src/daemon/Display.cpp#L345

which always returns `TRUE` for an absolute pathname. It means autologin is always attempted as Wayland, resulting in

 ```
Oct 29 19:32:04 uefi sddm-helper[1152]: Starting: "/usr/share/sddm/scripts/wayland-session /usr/bin/startplasma-x11"
```

Which obviously fails. The problem is, by default autologin session is `NULL` and so sddm reads the last session from state file. But last session name is always stored as the absolute pathname:

```
uefi:~ # cat /var/lib/sddm/
.cache/     .config/    .local/     state.conf  
uefi:~ # cat /var/lib/sddm/state.conf 
[Last]
# Name of the last logged-in user.
# This user will be preselected when the login screen appears
User=user


# Name of the session for the last logged-in user.
# This session will be preselected when the login screen appears.
Session=/usr/share/xsessions/plasma5.desktop
uefi:~ # 
```

so if the last session was X11, subsequent autologin will always fail.

**Comment by Vogtinator** [comment] 2023-03-20 08:01
Duplicate of #1348, fixed with https://github.com/sddm/sddm/pull/1355

**Closed as not planned by Vogtinator** 2023-03-20 08:01 UTC
Labels: bug, duplicate
