### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by arcolinuxz** [sddm/sddm#1677] opened 2023-03-04 06:07 UTC
Could you make a new release?

the sddm-git version (latest code) proves to be better than sddm now on Arch Linux. - 0.19.0-9
see https://github.com/sddm/sddm/issues/1476#issuecomment-1454414549

**Comment by arcolinuxz** [comment] 2023-03-04 06:13
Will test out sddm-git-0.19.0.201.g676fb59-1-x86_64.pkg.tar.zst and will let you know if all is well with this latest code.

Arch Linux based

Ok on ArcoLinux Xfce4
Ok on ArcoLinux Hyprland - wayland
Ok on ArcoLinux Plasma X11 and wayland

![Screenshot_20230304_081812](https://user-images.githubusercontent.com/36679406/222881946-627a62d3-9d1f-4944-a546-f471c3ced939.png)

No issues on our end

**Comment by mcendu** [comment] 2023-03-06 05:27
duplicate of #1471

**Closed as not planned** 2023-03-06 13:28 UTC
